package com.boare.cadencii;

public class KeysUtil{
    public static int getValue( Keys keys ){
        switch( keys ){
            case Modifiers:
                return -65536;
            case None:
                return 0;
            case LButton:
                return 1;
            case RButton:
                return 2;
            case Cancel:
                return 3;
            case MButton:
                return 4;
            case XButton1:
                return 5;
            case XButton2:
                return 6;
            case Back:
                return 8;
            case Tab:
                return 9;
            case LineFeed:
                return 10;
            case Clear:
                return 12;
            case Enter:
                return 13;
            case Return:
                return 13;
            case ShiftKey:
                return 16;
            case ControlKey:
                return 17;
            case Menu:
                return 18;
            case Pause:
                return 19;
            case CapsLock:
                return 20;
            case Capital:
                return 20;
            case KanaMode:
                return 21;
            case HanguelMode:
                return 21;
            case HangulMode:
                return 21;
            case JunjaMode:
                return 23;
            case FinalMode:
                return 24;
            case KanjiMode:
                return 25;
            case HanjaMode:
                return 25;
            case Escape:
                return 27;
            case IMEConvert:
                return 28;
            case IMENonconvert:
                return 29;
            case IMEAceept:
                return 30;
            case IMEAccept:
                return 30;
            case IMEModeChange:
                return 31;
            case Space:
                return 32;
            case Prior:
                return 33;
            case PageUp:
                return 33;
            case Next:
                return 34;
            case PageDown:
                return 34;
            case End:
                return 35;
            case Home:
                return 36;
            case Left:
                return 37;
            case Up:
                return 38;
            case Right:
                return 39;
            case Down:
                return 40;
            case Select:
                return 41;
            case Print:
                return 42;
            case Execute:
                return 43;
            case PrintScreen:
                return 44;
            case Snapshot:
                return 44;
            case Insert:
                return 45;
            case Delete:
                return 46;
            case Help:
                return 47;
            case D0:
                return 48;
            case D1:
                return 49;
            case D2:
                return 50;
            case D3:
                return 51;
            case D4:
                return 52;
            case D5:
                return 53;
            case D6:
                return 54;
            case D7:
                return 55;
            case D8:
                return 56;
            case D9:
                return 57;
            case A:
                return 65;
            case B:
                return 66;
            case C:
                return 67;
            case D:
                return 68;
            case E:
                return 69;
            case F:
                return 70;
            case G:
                return 71;
            case H:
                return 72;
            case I:
                return 73;
            case J:
                return 74;
            case K:
                return 75;
            case L:
                return 76;
            case M:
                return 77;
            case N:
                return 78;
            case O:
                return 79;
            case P:
                return 80;
            case Q:
                return 81;
            case R:
                return 82;
            case S:
                return 83;
            case T:
                return 84;
            case U:
                return 85;
            case V:
                return 86;
            case W:
                return 87;
            case X:
                return 88;
            case Y:
                return 89;
            case Z:
                return 90;
            case LWin:
                return 91;
            case RWin:
                return 92;
            case Apps:
                return 93;
            case Sleep:
                return 95;
            case NumPad0:
                return 96;
            case NumPad1:
                return 97;
            case NumPad2:
                return 98;
            case NumPad3:
                return 99;
            case NumPad4:
                return 100;
            case NumPad5:
                return 101;
            case NumPad6:
                return 102;
            case NumPad7:
                return 103;
            case NumPad8:
                return 104;
            case NumPad9:
                return 105;
            case Multiply:
                return 106;
            case Add:
                return 107;
            case Separator:
                return 108;
            case Subtract:
                return 109;
            case Decimal:
                return 110;
            case Divide:
                return 111;
            case F1:
                return 112;
            case F2:
                return 113;
            case F3:
                return 114;
            case F4:
                return 115;
            case F5:
                return 116;
            case F6:
                return 117;
            case F7:
                return 118;
            case F8:
                return 119;
            case F9:
                return 120;
            case F10:
                return 121;
            case F11:
                return 122;
            case F12:
                return 123;
            case F13:
                return 124;
            case F14:
                return 125;
            case F15:
                return 126;
            case F16:
                return 127;
            case F17:
                return 128;
            case F18:
                return 129;
            case F19:
                return 130;
            case F20:
                return 131;
            case F21:
                return 132;
            case F22:
                return 133;
            case F23:
                return 134;
            case F24:
                return 135;
            case NumLock:
                return 144;
            case Scroll:
                return 145;
            case LShiftKey:
                return 160;
            case RShiftKey:
                return 161;
            case LControlKey:
                return 162;
            case RControlKey:
                return 163;
            case LMenu:
                return 164;
            case RMenu:
                return 165;
            case BrowserBack:
                return 166;
            case BrowserForward:
                return 167;
            case BrowserRefresh:
                return 168;
            case BrowserStop:
                return 169;
            case BrowserSearch:
                return 170;
            case BrowserFavorites:
                return 171;
            case BrowserHome:
                return 172;
            case VolumeMute:
                return 173;
            case VolumeDown:
                return 174;
            case VolumeUp:
                return 175;
            case MediaNextTrack:
                return 176;
            case MediaPreviousTrack:
                return 177;
            case MediaStop:
                return 178;
            case MediaPlayPause:
                return 179;
            case LaunchMail:
                return 180;
            case SelectMedia:
                return 181;
            case LaunchApplication1:
                return 182;
            case LaunchApplication2:
                return 183;
            case Oem1:
                return 186;
            case OemSemicolon:
                return 186;
            case Oemplus:
                return 187;
            case Oemcomma:
                return 188;
            case OemMinus:
                return 189;
            case OemPeriod:
                return 190;
            case OemQuestion:
                return 191;
            case Oem2:
                return 191;
            case Oemtilde:
                return 192;
            case Oem3:
                return 192;
            case Oem4:
                return 219;
            case OemOpenBrackets:
                return 219;
            case OemPipe:
                return 220;
            case Oem5:
                return 220;
            case Oem6:
                return 221;
            case OemCloseBrackets:
                return 221;
            case Oem7:
                return 222;
            case OemQuotes:
                return 222;
            case Oem8:
                return 223;
            case Oem102:
                return 226;
            case OemBackslash:
                return 226;
            case ProcessKey:
                return 229;
            case Packet:
                return 231;
            case Attn:
                return 246;
            case Crsel:
                return 247;
            case Exsel:
                return 248;
            case EraseEof:
                return 249;
            case Play:
                return 250;
            case Zoom:
                return 251;
            case NoName:
                return 252;
            case Pa1:
                return 253;
            case OemClear:
                return 254;
            case KeyCode:
                return 65535;
            case Shift:
                return 65536;
            case Control:
                return 131072;
            case Alt:
                return 262144;
        }
        return 0;
    }
}
