//this file was autogenerated by makeRes
//makeRes -i ./Cadencii/Resources.list -o ./Cadencii/Resources.cs -p org.kbinani.cadencii -n org.kbinani.cadencii
#if JAVA
package org.kbinani.cadencii;

import java.awt.*;
import java.io.*;
import javax.imageio.*;
import javax.swing.*;
import org.kbinani.*;
#else
using System;
using System.IO;
using org.kbinani;
using org.kbinani.java.awt;

namespace org.kbinani.cadencii{
#endif

    public class Resources{
        private static String basePath = null;
        private static String getBasePath(){
            if( basePath == null ){
                basePath = PortUtil.combinePath( PortUtil.getApplicationStartupPath(), "resources" );
            }
            return basePath;
        }

    }
#if !JAVA
}
#endif
