/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloCallBack */

#ifndef _Included_HelloCallBack
#define _Included_HelloCallBack
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HelloCallBack
 * Method:    test
 * Signature: (LHelloCallBackMe;)V
 */
JNIEXPORT void JNICALL Java_HelloCallBack_test
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
