apputil:
	javac org_kbinani_apputil.java -encoding UTF-8

corlib:
	javac org_kbinani.java -encoding UTF-8

media:
	javac org_kbinani_media.java -encoding UTF-8

vsq:
	javac org_kbinani_vsq.java -encoding UTF-8

Cadencii:
	javac org_kbinani_Cadencii.java -encoding UTF-8

all:
	$(MAKE) corlib
	$(MAKE) apputil
	$(MAKE) media
	$(MAKE) vsq
	$(MAKE) Cadencii
