/*
 * SymbolTable.cs
 * Copyright (C) 2008-2010 kbinani
 *
 * This file is part of org.kbinani.vsq.
 *
 * org.kbinani.vsq is free software; you can redistribute it and/or
 * modify it under the terms of the BSD License.
 *
 * org.kbinani.vsq is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
#if JAVA
package org.kbinani.vsq;

import java.util.*;
import java.io.*;
import org.kbinani.*;
#else
using System;
using System.Text;
using System.Windows.Forms;
using org.kbinani;
using org.kbinani.java.util;
using org.kbinani.java.io;

namespace org.kbinani.vsq {
    using boolean = System.Boolean;
    using Integer = System.Int32;
#endif

#if JAVA
    public class SymbolTable implements Cloneable {
#else
    public class SymbolTable : ICloneable {
#endif
        private TreeMap<String, String> m_dict;
        private String m_name;
        private boolean m_enabled;

        #region Static Field
        private static TreeMap<Integer, SymbolTable> s_table = new TreeMap<Integer, SymbolTable>();
        private static SymbolTable s_default_jp = null;
        private static SymbolTable s_default_en = null;
        private static boolean s_initialized = false;
        #region KEY_EN
#if JAVA
        public static final String[][] _KEY_EN = {
#else
        public static readonly String[,] _KEY_EN = {
#endif
            {"ace", "eI s"},
            {"ache", "eI k"},
            {"act", "{ k t"},
            {"add", "{ d"},
            {"aft", "{ f t"},
            {"age", "eI dZ"},
            {"aged", "eI dZ d"},
            {"aid", "eI d"},
            {"ail", "eI l"},
            {"aim", "eI m"},
            {"air", "e@"},
            {"ape", "eI p"},
            {"arc", "Q@ k"},
            {"arch", "Q@ tS"},
            {"arched", "Q@ tS t"},
            {"arm", "Q@ m"},
            {"art", "Q@ t"},
            {"ash", "{ S"},
            {"ask", "{ s k"},
            {"aunt", "{ n t"},
            {"awe", "Q"},
            {"ax", "{ k s"},
            {"axe", "{ k s"},
            {"back", "bh { k"},
            {"bad", "bh { d"},
            {"BAD", "bh { d"},
            {"badge", "bh { dZ"},
            {"bag", "bh { g"},
            {"bail", "bh eI l"},
            {"bait", "bh eI t"},
            {"bake", "bh eI k"},
            {"bald", "bh O: l d"},
            {"bale", "bh eI l"},
            {"balk", "bh O: k"},
            {"ball", "bh O: l"},
            {"balm", "bh Q m"},
            {"ban", "bh { n"},
            {"band", "bh { n d"},
            {"bang", "bh { N"},
            {"bank", "bh { N k"},
            {"bar", "bh Q@"},
            {"barb", "bh Q@ b"},
            {"bard", "bh Q@ d"},
            {"bare", "bh e@"},
            {"BARE", "bh e@"},
            {"barge", "bh Q@ dZ"},
            {"bark", "bh Q@ k"},
            {"base", "bh eI s"},
            {"bat", "bh { t"},
            {"batch", "bh { tS"},
            {"bath", "bh { T"},
            {"bathe", "bh eI D"},
            {"bawl", "bh O: l"},
            {"bay", "bh eI"},
            {"be", "bh i:"},
            {"beach", "bh i: tS"},
            {"bead", "bh i: d"},
            {"beak", "bh i: k"},
            {"beam", "bh i: m"},
            {"bean", "bh i: n"},
            {"bear", "bh e@"},
            {"beard", "bh I@ d"},
            {"beat", "bh i: t"},
            {"bed", "bh e d"},
            {"beep", "bh i: p"},
            {"beer", "bh I@"},
            {"beg", "bh e g"},
            {"beige", "bh eI Z"},
            {"belch", "bh e l tS"},
            {"bell", "bh e l"},
            {"belt", "bh e l t"},
            {"bench", "bh e n tS"},
            {"bend", "bh e n d"},
            {"berth", "bh @r T"},
            {"best", "bh e s t"},
            {"bet", "bh e t"},
            {"bid", "bh I d"},
            {"big", "bh I g"},
            {"bile", "bh aI l"},
            {"bill", "bh I l"},
            {"bin", "bh I n"},
            {"bind", "bh aI n d"},
            {"birch", "bh @r tS"},
            {"bird", "bh @r d"},
            {"birth", "bh @r T"},
            {"bite", "bh aI t"},
            {"black", "bh l { k"},
            {"blame", "bh l eI m"},
            {"bland", "bh l { n d"},
            {"blank", "bh l { N k"},
            {"blare", "bh l e@"},
            {"blast", "bh l { s t"},
            {"blaze", "bh l eI z"},
            {"bleach", "bh l i: tS"},
            {"bleak", "bh l i: k"},
            {"bleep", "bh l i: p"},
            {"blend", "bh l e n d"},
            {"bless", "bh l e s"},
            {"blessed", "bh l e s t"},
            {"BLESSED", "bh l e s t"},
            {"blight", "bh l aI t"},
            {"blind", "bh l aI n d"},
            {"BLIND", "bh l aI n d"},
            {"blink", "bh l I N k"},
            {"blithe", "bh l aI D"},
            {"blitz", "bh l I t s"},
            {"bloat", "bh l @U t"},
            {"blob", "bh l Q b"},
            {"block", "bh l Q k"},
            {"blood", "bh l V d"},
            {"bloom", "bh l u: m"},
            {"blot", "bh l Q t"},
            {"blow", "bh l @U"},
            {"blue", "bh l u:"},
            {"bluff", "bh l V f"},
            {"blunt", "bh l V n t"},
            {"blur", "bh l @r"},
            {"blush", "bh l V S"},
            {"board", "bh O@ d"},
            {"boast", "bh @U s t"},
            {"boat", "bh @U t"},
            {"bob", "bh Q b"},
            {"bog", "bh Q g"},
            {"boil", "bh OI l"},
            {"bold", "bh @U l d"},
            {"bolt", "bh @U l t"},
            {"bomb", "bh Q m"},
            {"bond", "bh Q n d"},
            {"bone", "bh @U n"},
            {"boo", "bh u:"},
            {"book", "bh U k"},
            {"Boole", "bh u: l"},
            {"boom", "bh u: m"},
            {"boost", "bh u: s t"},
            {"boot", "bh u: t"},
            {"bop", "bh Q p"},
            {"bore", "bh O@"},
            {"botch", "bh Q tS"},
            {"bounce", "bh aU n s"},
            {"bound", "bh aU n d"},
            {"BOUND", "bh aU n d"},
            {"bow", "bh aU"},
            {"bowl", "bh @U l"},
            {"box", "bh Q k s"},
            {"brace", "bh r eI s"},
            {"brad", "bh r { d"},
            {"brag", "bh r { g"},
            {"braid", "bh r eI d"},
            {"braille", "bh r eI l"},
            {"Braille", "bh r eI l"},
            {"brain", "bh r eI n"},
            {"brake", "bh r eI k"},
            {"branch", "bh r { n tS"},
            {"brand", "bh r { n d"},
            {"brash", "bh r { S"},
            {"brass", "bh r { s"},
            {"brave", "bh r eI v"},
            {"brawl", "bh r O: l"},
            {"brawn", "bh r O: n"},
            {"bray", "bh r eI"},
            {"breach", "bh r i: tS"},
            {"bread", "bh r e d"},
            {"break", "bh r eI k"},
            {"breast", "bh r e s t"},
            {"breathe", "bh r i: D"},
            {"breed", "bh r i: d"},
            {"breeze", "bh r i: z"},
            {"brew", "bh r u:"},
            {"bribe", "bh r aI b"},
            {"bride", "bh r aI d"},
            {"bridge", "bh r I dZ"},
            {"brief", "bh r i: f"},
            {"bright", "bh r aI t"},
            {"brim", "bh r I m"},
            {"brine", "bh r aI n"},
            {"bring", "bh r I N"},
            {"broad", "bh r O: d"},
            {"broil", "bh r OI l"},
            {"bronze", "bh r Q n z"},
            {"brooch", "bh r @U tS"},
            {"brood", "bh r u: d"},
            {"broom", "bh r u: m"},
            {"brown", "bh r aU n"},
            {"browse", "bh r aU z"},
            {"bruise", "bh r u: z"},
            {"brunch", "bh r V n tS"},
            {"brush", "bh r V S"},
            {"brusque", "bh r V s k"},
            {"buck", "bh V k"},
            {"bud", "bh V d"},
            {"buff", "bh V f"},
            {"bug", "bh V g"},
            {"build", "bh I l d"},
            {"bulb", "bh V l b"},
            {"bulge", "bh V l dZ"},
            {"bulk", "bh V l k"},
            {"bull", "bh U l"},
            {"bum", "bh V m"},
            {"bump", "bh V m p"},
            {"bunch", "bh V n tS"},
            {"bung", "bh V N"},
            {"bunk", "bh V N k"},
            {"bunt", "bh V n"},
            {"bur", "bh @r"},
            {"burl", "bh @r l"},
            {"burn", "bh @r n"},
            {"burp", "bh @r p"},
            {"burst", "bh @r s t"},
            {"bus", "bh V s"},
            {"bush", "bh U S"},
            {"butch", "bh U tS"},
            {"butt", "bh V t"},
            {"buy", "bh aI"},
            {"buzz", "bh V z"},
            {"cache", "kh { S"},
            {"cage", "kh eI dZ"},
            {"calk", "kh O: k"},
            {"call", "kh O: l"},
            {"Call", "kh O: l"},
            {"calm", "kh Q m"},
            {"camp", "kh { m p"},
            {"can", "kh { n"},
            {"cane", "kh eI n"},
            {"cant", "kh { n t"},
            {"cap", "kh { p"},
            {"card", "kh Q@ d"},
            {"care", "kh e@"},
            {"cart", "kh Q@ t"},
            {"carve", "kh Q@ v"},
            {"case", "kh eI s"},
            {"cash", "kh { S"},
            {"cast", "kh { s t"},
            {"cat", "kh { t"},
            {"catch", "kh { tS"},
            {"cause", "kh Q z"},
            {"cave", "kh eI v"},
            {"caw", "kh O:"},
            {"cease", "s i: s"},
            {"cell", "s e l"},
            {"Celt", "s e l t"},
            {"Chad", "tS { d"},
            {"chafe", "tS eI f"},
            {"chaff", "tS { f"},
            {"chain", "tS eI n"},
            {"chair", "tS e@"},
            {"chalk", "tS Q k"},
            {"chance", "tS { n s"},
            {"change", "tS eI n dZ"},
            {"chant", "tS { n t"},
            {"chap", "tS { p"},
            {"char", "tS Q@"},
            {"charge", "tS Q@ dZ"},
            {"Charles", "tS Q@ l z"},
            {"charm", "tS Q@ m"},
            {"chart", "tS Q@ t"},
            {"chase", "tS eI s"},
            {"chasse", "tS { s"},
            {"chaste", "tS eI s t"},
            {"chat", "tS { t"},
            {"chaw", "tS O:"},
            {"cheap", "tS i: p"},
            {"CHEAP", "tS i: p"},
            {"cheat", "tS i: t"},
            {"check", "tS e k"},
            {"cheek", "tS i: k"},
            {"cheer", "tS I@"},
            {"chert", "tS @r t"},
            {"chew", "tS u:"},
            {"chic", "S i: k"},
            {"child", "tS aI l d"},
            {"chill", "tS I l"},
            {"chime", "tS aI m"},
            {"chink", "tS I N k"},
            {"chip", "tS I p"},
            {"chirp", "tS @r p"},
            {"chock", "tS Q k"},
            {"choice", "tS OI s"},
            {"choke", "tS @U k"},
            {"chomp", "tS Q m p"},
            {"choose", "tS u: z"},
            {"chop", "tS Q p"},
            {"chord", "kh O@ d"},
            {"chrome", "kh r @U m"},
            {"chug", "tS V g"},
            {"church", "tS @r tS"},
            {"churn", "tS @r n"},
            {"chute", "S u: t"},
            {"cinch", "s I n tS"},
            {"clack", "kh l { k"},
            {"claim", "kh l eI m"},
            {"clam", "kh l { m"},
            {"clamp", "kh l { m p"},
            {"clang", "kh l { N"},
            {"clank", "kh l { N k"},
            {"clap", "kh l { p"},
            {"clash", "kh l { S"},
            {"clasp", "kh l { s p"},
            {"class", "kh l { s"},
            {"clause", "kh l O: z"},
            {"claw", "kh l O:"},
            {"clean", "kh l i: n"},
            {"cleanse", "kh l e n z"},
            {"clear", "kh l I@"},
            {"cleat", "kh l i: t"},
            {"cleave", "kh l i: v"},
            {"cleft", "kh l e f t"},
            {"clench", "kh l e n tS"},
            {"clerk", "kh l @r k"},
            {"click", "kh l I k"},
            {"climb", "kh l aI m"},
            {"clinch", "kh l I n tS"},
            {"clink", "kh l I N k"},
            {"clip", "kh l I p"},
            {"cloak", "kh l @U k"},
            {"clock", "kh l Q k"},
            {"clog", "kh l Q g"},
            {"clone", "kh l @U n"},
            {"close", "kh l @U s"},
            {"CLOSE", "kh l @U s"},
            {"CLOSED", "kh l @U z d"},
            {"clot", "kh l Q t"},
            {"cloud", "kh l aU d"},
            {"clout", "kh l aU t"},
            {"clown", "kh l aU n"},
            {"club", "kh l V b"},
            {"cluck", "kh l V k"},
            {"clutch", "kh l V tS"},
            {"coach", "kh @U tS"},
            {"coal", "kh @U l"},
            {"coarse", "kh O@ s"},
            {"coast", "kh @U s t"},
            {"coat", "kh @U t"},
            {"cock", "kh Q k"},
            {"cod", "kh Q d"},
            {"code", "kh @U d"},
            {"cog", "kh O: g"},
            {"coil", "kh OI l"},
            {"coin", "kh OI n"},
            {"coke", "kh @U k"},
            {"cold", "kh @U l d"},
            {"COLD", "kh @U l d"},
            {"comb", "kh @U m"},
            {"come", "kh V m"},
            {"con", "kh Q n"},
            {"cone", "kh @U n"},
            {"conk", "kh Q N k"},
            {"coo", "kh u:"},
            {"cook", "kh U k"},
            {"cool", "kh u: l"},
            {"COOL", "kh u: l"},
            {"cope", "kh @U p"},
            {"cord", "kh O@ d"},
            {"core", "kh O@"},
            {"cork", "kh O@ k"},
            {"corn", "kh O@ n"},
            {"cost", "kh Q s t"},
            {"cough", "kh Q f"},
            {"count", "kh aU n t"},
            {"course", "kh O@ s"},
            {"court", "kh O@ t"},
            {"cowl", "kh aU l"},
            {"cox", "kh Q k s"},
            {"coy", "kh OI"},
            {"crab", "kh r { b"},
            {"crabbed", "kh r { b d"},
            {"crack", "kh r { k"},
            {"craft", "kh r { f t"},
            {"cram", "kh r { m"},
            {"cramp", "kh r { m p"},
            {"crane", "kh r eI n"},
            {"crank", "kh r { N k"},
            {"crap", "kh r { p"},
            {"crash", "kh r { S"},
            {"crass", "kh r { s"},
            {"crate", "kh r eI t"},
            {"crave", "kh r eI v"},
            {"crawl", "kh r O: l"},
            {"craze", "kh r eI z"},
            {"creak", "kh r i: k"},
            {"cream", "kh r i: m"},
            {"creed", "kh r i: d"},
            {"creep", "kh r i: p"},
            {"crepe", "kh r eI p"},
            {"crest", "kh r e s t"},
            {"crew", "kh r u:"},
            {"crib", "kh r I b"},
            {"crick", "kh r I k"},
            {"crime", "kh r aI m"},
            {"crimp", "kh r I m p"},
            {"crisp", "kh r I s p"},
            {"croak", "kh r @U k"},
            {"crock", "kh r Q k"},
            {"crook", "kh r U k"},
            {"croon", "kh r u: n"},
            {"crop", "kh r Q p"},
            {"cross", "kh r O: s"},
            {"crouch", "kh r aU tS"},
            {"croup", "kh r u: p"},
            {"crow", "kh r @U"},
            {"crowd", "kh r aU d"},
            {"crown", "kh r aU n"},
            {"Crown", "kh r aU n"},
            {"crude", "kh r u: d"},
            {"cruise", "kh r u: z"},
            {"crumb", "kh r V m"},
            {"crunch", "kh r V n tS"},
            {"crush", "kh r V S"},
            {"crust", "kh r V s t"},
            {"cry", "kh r aI"},
            {"cub", "kh V b"},
            {"cube", "kh j u: b"},
            {"cue", "kh j u:"},
            {"cull", "kh V l"},
            {"cult", "kh V l t"},
            {"cup", "kh V p"},
            {"curb", "kh @r b"},
            {"cure", "kh j U@"},
            {"curl", "kh @r l"},
            {"curse", "kh @r s"},
            {"curve", "kh @r v"},
            {"CURVED", "kh @r v d"},
            {"cusp", "kh V s p"},
            {"cussed", "kh V s t"},
            {"cut", "kh V t"},
            {"cyst", "s I s t"},
            {"czar", "z Q@"},
            {"Czech", "tS e k"},
            {"dab", "dh { b"},
            {"dam", "dh { m"},
            {"damned", "dh { m d"},
            {"damp", "dh { m p"},
            {"dance", "dh { n s"},
            {"dare", "dh e@"},
            {"dark", "dh Q@ k"},
            {"DARK", "dh Q@ k"},
            {"darn", "dh Q@ n"},
            {"dart", "dh Q@ t"},
            {"dash", "dh { S"},
            {"date", "dh eI t"},
            {"daub", "dh O: b"},
            {"dawn", "dh O: n"},
            {"day", "dh eI"},
            {"daze", "dh eI z"},
            {"dead", "dh e d"},
            {"DEAD", "dh e d"},
            {"deaf", "dh e f"},
            {"deal", "dh i: l"},
            {"dean", "dh i: n"},
            {"death", "dh e T"},
            {"Death", "dh e T"},
            {"deep", "dh i: p"},
            {"deft", "dh e f t"},
            {"dense", "dh e n s"},
            {"dent", "dh e n t"},
            {"dew", "dh u:"},
            {"dice", "dh aI s"},
            {"die", "dh aI"},
            {"dig", "dh I g"},
            {"dike", "dh aI k"},
            {"dim", "dh I m"},
            {"dine", "dh aI n"},
            {"dip", "dh I p"},
            {"dirt", "dh @r t"},
            {"dish", "dh I S"},
            {"ditch", "dh I tS"},
            {"dive", "dh aI v"},
            {"do", "dh u:"},
            {"dock", "dh Q k"},
            {"dodge", "dh Q dZ"},
            {"dogged", "dh O: g d"},
            {"Donne", "dh V n"},
            {"doom", "dh u: m"},
            {"doomed", "dh u: m d"},
            {"dope", "dh @U p"},
            {"dose", "dh @U s"},
            {"doss", "dh O: s"},
            {"dot", "dh Q t"},
            {"dote", "dh @U t"},
            {"doubt", "dh aU t"},
            {"dough", "dh @U"},
            {"dove", "dh V v"},
            {"dower", "dh aU r"},
            {"down", "dh aU n"},
            {"DOWN", "dh aU n"},
            {"dowse", "dh aU s"},
            {"doze", "dh @U z"},
            {"drab", "dh r { b"},
            {"draft", "dh r { f t"},
            {"drag", "dh r { g"},
            {"drain", "dh r eI n"},
            {"drape", "dh r eI p"},
            {"draw", "dh r O:"},
            {"drawer", "dh r O@"},
            {"drawl", "dh r O: l"},
            {"dream", "dh r i: m"},
            {"dredge", "dh r e dZ"},
            {"dress", "dh r e s"},
            {"drift", "dh r I f t"},
            {"drill", "dh r I l"},
            {"drink", "dh r I N k"},
            {"drip", "dh r I p"},
            {"drive", "dh r aI v"},
            {"drone", "dh r @U n"},
            {"drool", "dh r u: l"},
            {"droop", "dh r u: p"},
            {"drop", "dh r Q p"},
            {"drudge", "dh r V dZ"},
            {"drug", "dh r V g"},
            {"drum", "dh r V m"},
            {"drunk", "dh r V N k"},
            {"drupe", "dh r u: p"},
            {"dry", "dh r aI"},
            {"DRY", "dh r aI"},
            {"dub", "dh V b"},
            {"duck", "dh V k"},
            {"duke", "dh u: k"},
            {"dull", "dh V l"},
            {"DULL", "dh V l"},
            {"dump", "dh V m p"},
            {"dun", "dh V n"},
            {"dung", "dh V N"},
            {"dunk", "dh V N k"},
            {"dust", "dh V s t"},
            {"Dutch", "dh V tS"},
            {"dwarf", "dh w O@ f"},
            {"dye", "dh aI"},
            {"earl", "@r l"},
            {"earn", "@r n"},
            {"earth", "@r T"},
            {"Earth", "@r T"},
            {"ease", "i: z"},
            {"eat", "i: t"},
            {"ebb", "e b"},
            {"edge", "e dZ"},
            {"egg", "e g"},
            {"end", "e n d"},
            {"err", "e@"},
            {"etch", "e tS"},
            {"eye", "aI"},
            {"face", "f eI s"},
            {"fad", "f { d"},
            {"fade", "f eI d"},
            {"fail", "f eI l"},
            {"faint", "f eI n t"},
            {"fair", "f e@"},
            {"fake", "f eI k"},
            {"fall", "f Q l"},
            {"Fall", "f Q l"},
            {"false", "f O: l s"},
            {"FALSE", "f O: l s"},
            {"fame", "f eI m"},
            {"fan", "f { n"},
            {"far", "f Q@"},
            {"farce", "f Q@ s"},
            {"fare", "f e@"},
            {"farm", "f Q@ m"},
            {"fast", "f { s t"},
            {"fat", "f { t"},
            {"fault", "f O: l t"},
            {"Faust", "f aU s t"},
            {"fawn", "f O: n"},
            {"fax", "f { k s"},
            {"fear", "f I@"},
            {"feast", "f i: s t"},
            {"feed", "f i: d"},
            {"feel", "f i: l"},
            {"feign", "f eI n"},
            {"feint", "f eI n t"},
            {"fell", "f e l"},
            {"felt", "f e l t"},
            {"fence", "f e n s"},
            {"fern", "f @r n"},
            {"fete", "f eI t"},
            {"feud", "f j u: d"},
            {"few", "f j u:"},
            {"FEW", "f j u:"},
            {"fief", "f i: f"},
            {"field", "f i: l d"},
            {"fierce", "f I@ s"},
            {"fifth", "f I f T"},
            {"fight", "f aI t"},
            {"file", "f aI l"},
            {"fill", "f I l"},
            {"filled", "f I l d"},
            {"film", "f I l m"},
            {"filth", "f I l T"},
            {"fin", "f I n"},
            {"find", "f aI n d"},
            {"fine", "f aI n"},
            {"FINE", "f aI n"},
            {"fink", "f I N k"},
            {"firm", "f @r m"},
            {"fisc", "f I s k"},
            {"fish", "f I S"},
            {"fit", "f I t"},
            {"fix", "f I k s"},
            {"fixed", "f I k s t"},
            {"fizz", "f I z"},
            {"flab", "f l { b"},
            {"flag", "f l { g"},
            {"flail", "f l eI l"},
            {"flame", "f l eI m"},
            {"flank", "f l { N k"},
            {"flap", "f l { p"},
            {"flare", "f l e@"},
            {"flash", "f l { S"},
            {"flat", "f l { t"},
            {"FLAT", "f l { t"},
            {"flaunt", "f l O: n t"},
            {"flaw", "f l O:"},
            {"flee", "f l i:"},
            {"fleece", "f l i: s"},
            {"fleer", "f l I@"},
            {"fleet", "f l i: t"},
            {"flesh", "f l e S"},
            {"flex", "f l e k s"},
            {"flick", "f l I k"},
            {"flight", "f l aI t"},
            {"flinch", "f l I n tS"},
            {"fling", "f l I N"},
            {"flint", "f l I n t"},
            {"flip", "f l I p"},
            {"flirt", "f l @r t"},
            {"flit", "f l I t"},
            {"float", "f l @U t"},
            {"flock", "f l Q k"},
            {"flog", "f l Q g"},
            {"flood", "f l V d"},
            {"floor", "f l O@"},
            {"FLOORED", "f l O@ d"},
            {"flop", "f l Q p"},
            {"floss", "f l Q s"},
            {"flounce", "f l aU n s"},
            {"flow", "f l @U"},
            {"fluff", "f l V f"},
            {"flush", "f l V S"},
            {"flute", "f l u: t"},
            {"flux", "f l V k s"},
            {"fly", "f l aI"},
            {"foal", "f @U l"},
            {"foam", "f @U m"},
            {"foe", "f @U"},
            {"fog", "f Q g"},
            {"foil", "f OI l"},
            {"fold", "f @U l d"},
            {"fool", "f u: l"},
            {"foot", "f U t"},
            {"force", "f O@ s"},
            {"forced", "f O@ s t"},
            {"ford", "f O@ d"},
            {"fore", "f O@"},
            {"forge", "f O@ dZ"},
            {"fork", "f O@ k"},
            {"form", "f O@ m"},
            {"fort", "f O@ t"},
            {"foul", "f aU l"},
            {"FOUL", "f aU l"},
            {"FOUND", "f aU n d"},
            {"fowl", "f aU l"},
            {"fox", "f Q k s"},
            {"FRAIL", "f r eI l"},
            {"frame", "f r eI m"},
            {"free", "f r i:"},
            {"freeze", "f r i: z"},
            {"freight", "f r eI t"},
            {"French", "f r e n tS"},
            {"fresh", "f r e S"},
            {"fret", "f r e t"},
            {"Freud", "f r OI d"},
            {"friend", "f r e n d"},
            {"frill", "f r I l"},
            {"fringe", "f r I n dZ"},
            {"frisk", "f r I s k"},
            {"frock", "f r Q k"},
            {"frog", "f r Q g"},
            {"front", "f r V n t"},
            {"frost", "f r O: s t"},
            {"Frost", "f r O: s t"},
            {"froth", "f r O: T"},
            {"frown", "f r aU n"},
            {"fruit", "f r u: t"},
            {"frump", "f r V m p"},
            {"fry", "f r aI"},
            {"fuck", "f V k"},
            {"fudge", "f V dZ"},
            {"fugue", "f j u: g"},
            {"full", "f U l"},
            {"fume", "f j u: m"},
            {"fun", "f V n"},
            {"fund", "f V n d"},
            {"funk", "f V N k"},
            {"fur", "f @r"},
            {"fuse", "f j u: z"},
            {"fuss", "f V s"},
            {"fuzz", "f V z"},
            {"Gael", "gh eI l"},
            {"gag", "gh { g"},
            {"gain", "gh eI n"},
            {"gall", "gh O: l"},
            {"game", "gh eI m"},
            {"gang", "gh { N"},
            {"gap", "gh { p"},
            {"gape", "gh eI p"},
            {"gas", "gh { s"},
            {"gasp", "gh { s p"},
            {"gate", "gh eI t"},
            {"gauche", "gh @U S"},
            {"gauge", "gh eI dZ"},
            {"Gaul", "gh O: l"},
            {"Gauss", "gh aU s"},
            {"gauze", "gh O: z"},
            {"gay", "gh eI"},
            {"gaze", "gh eI z"},
            {"gel", "dZ e l"},
            {"gene", "dZ i: n"},
            {"George", "dZ O@ dZ"},
            {"germ", "dZ @r m"},
            {"get", "gh e t"},
            {"ghost", "gh @U s t"},
            {"gift", "gh I f t"},
            {"gild", "gh I l d"},
            {"gilt", "gh I l t"},
            {"gin", "dZ I n"},
            {"girl", "gh @r l"},
            {"give", "gh I v"},
            {"glad", "gh l { d"},
            {"glance", "gh l { n s"},
            {"gland", "gh l { n d"},
            {"glare", "gh l e@"},
            {"glass", "gh l { s"},
            {"glaze", "gh l eI z"},
            {"gleam", "gh l i: m"},
            {"glib", "gh l I b"},
            {"glide", "gh l aI d"},
            {"glimpse", "gh l I m p s"},
            {"gloat", "gh l @U t"},
            {"globe", "gh l @U b"},
            {"gloom", "gh l u: m"},
            {"gloss", "gh l O: s"},
            {"glow", "gh l @U"},
            {"glue", "gh l u:"},
            {"glum", "gh l V m"},
            {"glut", "gh l V t"},
            {"gnarl", "n Q@ l"},
            {"gnaw", "n O:"},
            {"go", "gh @U"},
            {"goad", "gh @U d"},
            {"God", "gh Q d"},
            {"Goethe", "gh @U T"},
            {"gold", "gh @U l d"},
            {"golf", "gh Q l f"},
            {"gong", "gh O: N"},
            {"good", "gh U d"},
            {"goose", "gh u: s"},
            {"gore", "gh O@"},
            {"gorge", "gh O@ dZ"},
            {"gouge", "gh aU dZ"},
            {"gout", "gh aU t"},
            {"gown", "gh aU n"},
            {"grab", "gh r { b"},
            {"grace", "gh r eI s"},
            {"grade", "gh r eI d"},
            {"graft", "gh r { f t"},
            {"grain", "gh r eI n"},
            {"grand", "gh r { n d"},
            {"grant", "gh r { n t"},
            {"grape", "gh r eI p"},
            {"graph", "gh r { f"},
            {"grasp", "gh r { s p"},
            {"grass", "gh r { s"},
            {"grate", "gh r eI t"},
            {"grave", "gh r eI v"},
            {"gray", "gh r eI"},
            {"graze", "gh r eI z"},
            {"grease", "gh r i: s"},
            {"great", "gh r eI t"},
            {"greed", "gh r i: d"},
            {"Greek", "gh r i: k"},
            {"green", "gh r i: n"},
            {"Green", "gh r i: n"},
            {"GREEN", "gh r i: n"},
            {"greet", "gh r i: t"},
            {"grey", "gh r eI"},
            {"grieve", "gh r i: v"},
            {"grill", "gh r I l"},
            {"grim", "gh r I m"},
            {"grin", "gh r I n"},
            {"grind", "gh r aI n d"},
            {"grip", "gh r I p"},
            {"gripe", "gh r aI p"},
            {"grit", "gh r I t"},
            {"groan", "gh r @U n"},
            {"groom", "gh r u: m"},
            {"groove", "gh r u: v"},
            {"grope", "gh r @U p"},
            {"gross", "gh r @U s"},
            {"GROSS", "gh r @U s"},
            {"grouch", "gh r aU tS"},
            {"ground", "gh r aU n d"},
            {"group", "gh r u: p"},
            {"grouse", "gh r aU s"},
            {"grout", "gh r aU t"},
            {"grow", "gh r @U"},
            {"growl", "gh r aU l"},
            {"growth", "gh r @U T"},
            {"grub", "gh r V b"},
            {"grudge", "gh r V dZ"},
            {"gruff", "gh r V f"},
            {"grunt", "gh r V n t"},
            {"guard", "gh Q@ d"},
            {"guess", "gh e s"},
            {"guide", "gh aI d"},
            {"guilt", "gh I l t"},
            {"gull", "gh V l"},
            {"gulp", "gh V l p"},
            {"gum", "gh V m"},
            {"gun", "gh V n"},
            {"gust", "gh V s t"},
            {"gut", "gh V t"},
            {"guy", "gh aI"},
            {"hack", "h { k"},
            {"hail", "h eI l"},
            {"hair", "h e@"},
            {"hale", "h eI l"},
            {"half", "h { f"},
            {"HALF", "h { f"},
            {"halt", "h O: l t"},
            {"ham", "h { m"},
            {"hand", "h { n d"},
            {"hang", "h { N"},
            {"hap", "h { p"},
            {"hard", "h Q@ d"},
            {"hare", "h e@"},
            {"harm", "h Q@ m"},
            {"harp", "h Q@ p"},
            {"harsh", "h Q@ S"},
            {"hash", "h { S"},
            {"haste", "h eI s t"},
            {"hat", "h { t"},
            {"hatch", "h { tS"},
            {"hate", "h eI t"},
            {"haul", "h O: l"},
            {"haunt", "h O: n t"},
            {"have", "h { v"},
            {"hawk", "h O: k"},
            {"haze", "h eI z"},
            {"head", "h e d"},
            {"heal", "h i: l"},
            {"health", "h e l T"},
            {"heap", "h i: p"},
            {"hear", "h I@"},
            {"heat", "h i: t"},
            {"heave", "h i: v"},
            {"hedge", "h e dZ"},
            {"heed", "h i: d"},
            {"heel", "h i: l"},
            {"heft", "h e f t"},
            {"heist", "h aI s t"},
            {"held", "h e l d"},
            {"Hell", "h e l"},
            {"help", "h e l p"},
            {"hem", "h e m"},
            {"herb", "@r b"},
            {"herd", "h @r d"},
            {"here", "h I@"},
            {"Hertz", "h e@ t s"},
            {"hew", "h j u:"},
            {"hide", "h aI d"},
            {"high", "h aI"},
            {"hike", "h aI k"},
            {"hill", "h I l"},
            {"hinge", "h I n dZ"},
            {"hint", "h I n t"},
            {"hiss", "h I s"},
            {"hit", "h I t"},
            {"hitch", "h I tS"},
            {"hive", "h aI v"},
            {"Hmong", "m O: N"},
            {"hoard", "h O@ d"},
            {"hoax", "h @U k s"},
            {"hob", "h Q b"},
            {"hock", "h Q k"},
            {"hoe", "h @U"},
            {"hog", "h Q g"},
            {"hoist", "h OI s t"},
            {"hold", "h @U l d"},
            {"hole", "h @U l"},
            {"home", "h @U m"},
            {"hone", "h @U n"},
            {"honk", "h Q N k"},
            {"hood", "h U d"},
            {"hoof", "h u: f"},
            {"hook", "h U k"},
            {"hoop", "h u: p"},
            {"hoot", "h u: t"},
            {"hop", "h Q p"},
            {"hope", "h @U p"},
            {"horn", "h O@ n"},
            {"horse", "h O@ s"},
            {"hose", "h @U z"},
            {"host", "h @U s t"},
            {"hot", "h Q t"},
            {"hound", "h aU n d"},
            {"house", "h aU s"},
            {"howl", "h aU l"},
            {"hue", "h j u:"},
            {"huff", "h V f"},
            {"hug", "h V g"},
            {"hull", "h V l"},
            {"hum", "h V m"},
            {"hunch", "h V n tS"},
            {"hunt", "h V n t"},
            {"hurl", "h @r l"},
            {"hurt", "h @r t"},
            {"hush", "h V S"},
            {"husk", "h V s k"},
            {"hymn", "h I m"},
            {"ice", "aI s"},
            {"ill", "I l"},
            {"ILL", "I l"},
            {"inch", "I n tS"},
            {"ink", "I N k"},
            {"isle", "aI l"},
            {"itch", "I tS"},
            {"jab", "dZ { b"},
            {"jack", "dZ { k"},
            {"jade", "dZ eI d"},
            {"jagged", "dZ { g d"},
            {"jail", "dZ eI l"},
            {"Jain", "dZ aI n"},
            {"jam", "dZ { m"},
            {"jar", "dZ Q@"},
            {"jaw", "dZ O:"},
            {"jazz", "dZ { z"},
            {"jeer", "dZ I@"},
            {"jerk", "dZ @r k"},
            {"jest", "dZ e s t"},
            {"jet", "dZ e t"},
            {"Jew", "dZ u:"},
            {"jib", "dZ I b"},
            {"jig", "dZ I g"},
            {"jilt", "dZ I l t"},
            {"jinx", "dZ I N k s"},
            {"jive", "dZ aI v"},
            {"job", "dZ Q b"},
            {"jog", "dZ Q g"},
            {"join", "dZ OI n"},
            {"joint", "dZ OI n t"},
            {"JOINT", "dZ OI n t"},
            {"joke", "dZ @U k"},
            {"jolt", "dZ @U l t"},
            {"joust", "dZ aU s t"},
            {"jowl", "dZ aU l"},
            {"joy", "dZ OI"},
            {"judge", "dZ V dZ"},
            {"jug", "dZ V g"},
            {"juice", "dZ u: s"},
            {"jump", "dZ V m p"},
            {"Jung", "j U N"},
            {"Kant", "kh { n t"},
            {"keen", "kh i: n"},
            {"keep", "kh i: p"},
            {"kern", "kh @r n"},
            {"key", "kh i:"},
            {"Keynes", "kh eI n z"},
            {"kick", "kh I k"},
            {"kid", "kh I d"},
            {"kill", "kh I l"},
            {"kin", "kh I n"},
            {"kind", "kh aI n d"},
            {"king", "kh I N"},
            {"kip", "kh I p"},
            {"kiss", "kh I s"},
            {"kit", "kh I t"},
            {"kite", "kh aI t"},
            {"kneel", "n i: l"},
            {"knell", "n e l"},
            {"knife", "n aI f"},
            {"knight", "n aI t"},
            {"knit", "n I t"},
            {"knock", "n Q k"},
            {"knot", "n Q t"},
            {"know", "n @U"},
            {"kook", "kh u: k"},
            {"lace", "l0 eI s"},
            {"lack", "l0 { k"},
            {"lag", "l0 { g"},
            {"lamb", "l0 { m"},
            {"lance", "l0 { n s"},
            {"land", "l0 { n d"},
            {"Lao", "l0 aU"},
            {"lap", "l0 { p"},
            {"lapse", "l0 { p s"},
            {"lard", "l0 Q@ d"},
            {"large", "l0 Q@ dZ"},
            {"lash", "l0 { S"},
            {"last", "l0 { s t"},
            {"LAST", "l0 { s t"},
            {"latch", "l0 { tS"},
            {"late", "l0 eI t"},
            {"LATE", "l0 eI t"},
            {"laud", "l0 O: d"},
            {"laugh", "l0 { f"},
            {"launch", "l0 O: n tS"},
            {"law", "l0 Q"},
            {"lax", "l0 { k s"},
            {"LAX", "l0 { k s"},
            {"lay", "l0 eI"},
            {"leach", "l0 i: tS"},
            {"lead", "l0 i: d"},
            {"leaf", "l0 i: f"},
            {"league", "l0 i: g"},
            {"leak", "l0 i: k"},
            {"lean", "l0 i: n"},
            {"LEAN", "l0 i: n"},
            {"leap", "l0 i: p"},
            {"learn", "l0 @r n"},
            {"lease", "l0 i: s"},
            {"leash", "l0 i: S"},
            {"least", "l0 i: s t"},
            {"leave", "l0 i: v"},
            {"leech", "l0 i: tS"},
            {"left", "l0 e f t"},
            {"LEFT", "l0 e f t"},
            {"leg", "l0 e g"},
            {"lend", "l0 e n d"},
            {"less", "l0 e s"},
            {"let", "l0 e t"},
            {"lewd", "l0 u: d"},
            {"lick", "l0 I k"},
            {"lie", "l0 aI"},
            {"liege", "l0 i: dZ"},
            {"life", "l0 aI f"},
            {"lift", "l0 I f t"},
            {"light", "l0 aI t"},
            {"LIGHT", "l0 aI t"},
            {"like", "l0 aI k"},
            {"lilt", "l0 I l t"},
            {"lime", "l0 aI m"},
            {"limp", "l0 I m p"},
            {"line", "l0 aI n"},
            {"link", "l0 I N k"},
            {"lisp", "l0 I s p"},
            {"list", "l0 I s t"},
            {"live", "l0 aI v"},
            {"load", "l0 @U d"},
            {"loam", "l0 @U m"},
            {"loan", "l0 @U n"},
            {"lob", "l0 Q b"},
            {"lobe", "l0 @U b"},
            {"lock", "l0 Q k"},
            {"lodge", "l0 Q dZ"},
            {"loft", "l0 O: f t"},
            {"log", "l0 O: g"},
            {"long", "l0 O: N"},
            {"look", "l0 U k"},
            {"loop", "l0 u: p"},
            {"loose", "l0 u: s"},
            {"LOOSE", "l0 u: s"},
            {"loot", "l0 u: t"},
            {"lope", "l0 @U p"},
            {"lord", "l0 O@ d"},
            {"Lord", "l0 O@ d"},
            {"lose", "l0 u: z"},
            {"loss", "l0 O: s"},
            {"lot", "l0 Q t"},
            {"lounge", "l0 aU n dZ"},
            {"louse", "l0 aU s"},
            {"love", "l0 V v"},
            {"low", "l0 @U"},
            {"LOW", "l0 @U"},
            {"luck", "l0 V k"},
            {"luff", "l0 V f"},
            {"lug", "l0 V g"},
            {"luge", "l0 u: dZ"},
            {"lull", "l0 V l"},
            {"lump", "l0 V m p"},
            {"lunch", "l0 V n tS"},
            {"lunge", "l0 V n dZ"},
            {"lurch", "l0 @r tS"},
            {"lure", "l0 U@"},
            {"lurk", "l0 @r k"},
            {"lust", "l0 V s t"},
            {"lute", "l0 u: t"},
            {"lymph", "l0 I m f"},
            {"lynch", "l0 I n tS"},
            {"Mace", "m eI s"},
            {"maid", "m eI d"},
            {"mail", "m eI l"},
            {"maim", "m eI m"},
            {"Maine", "m eI n"},
            {"make", "m eI k"},
            {"male", "m eI l"},
            {"malt", "m O: l t"},
            {"man", "m { n"},
            {"mange", "m eI n dZ"},
            {"Manx", "m { N k s"},
            {"map", "m { p"},
            {"mar", "m Q@"},
            {"march", "m Q@ tS"},
            {"mark", "m Q@ k"},
            {"Mars", "m Q@ z"},
            {"marsh", "m Q@ S"},
            {"mash", "m { S"},
            {"mask", "m { s k"},
            {"mass", "m { s"},
            {"match", "m { tS"},
            {"mate", "m eI t"},
            {"maul", "m O: l"},
            {"mauve", "m O: v"},
            {"maze", "m eI z"},
            {"meal", "m i: l"},
            {"mean", "m i: n"},
            {"meat", "m i: t"},
            {"meek", "m i: k"},
            {"meet", "m i: t"},
            {"meld", "m e l d"},
            {"melt", "m e l t"},
            {"mesh", "m e S"},
            {"mess", "m e s"},
            {"mew", "m j u:"},
            {"might", "m aI t"},
            {"milch", "m I l tS"},
            {"mile", "m aI l"},
            {"milk", "m I l k"},
            {"mill", "m I l"},
            {"mime", "m aI m"},
            {"mince", "m I n s"},
            {"mind", "m aI n d"},
            {"mine", "m aI n"},
            {"mint", "m I n t"},
            {"mire", "m aI r"},
            {"miss", "m I s"},
            {"mist", "m I s t"},
            {"mix", "m I k s"},
            {"mob", "m Q b"},
            {"mock", "m Q k"},
            {"mode", "m @U d"},
            {"mold", "m @U l d"},
            {"molt", "m @U l t"},
            {"month", "m V n T"},
            {"moon", "m u: n"},
            {"moor", "m U@"},
            {"mope", "m @U p"},
            {"more", "m O@"},
            {"moss", "m O: s"},
            {"most", "m @U s t"},
            {"moth", "m O: T"},
            {"mound", "m aU n d"},
            {"mount", "m aU n t"},
            {"mourn", "m O@ n"},
            {"mouse", "m aU s"},
            {"mousse", "m u: s"},
            {"mouth", "m aU T"},
            {"move", "m u: v"},
            {"mow", "m @U"},
            {"muck", "m V k"},
            {"mud", "m V d"},
            {"muff", "m V f"},
            {"mug", "m V g"},
            {"mulch", "m V l tS"},
            {"mule", "m j u: l"},
            {"mull", "m V l"},
            {"mum", "m V m"},
            {"munch", "m V n tS"},
            {"murk", "m @r k"},
            {"muse", "m j u: z"},
            {"mush", "m V S"},
            {"musk", "m V s k"},
            {"mute", "m j u: t"},
            {"myth", "m I T"},
            {"nag", "n { g"},
            {"nail", "n eI l"},
            {"name", "n eI m"},
            {"nap", "n { p"},
            {"nay", "n eI"},
            {"NEAR", "n I@"},
            {"neat", "n i: t"},
            {"neck", "n e k"},
            {"need", "n i: d"},
            {"nerve", "n @r v"},
            {"nest", "n e s t"},
            {"net", "n e t"},
            {"NEW", "n u:"},
            {"news", "n u: z"},
            {"nick", "n I k"},
            {"niece", "n i: s"},
            {"night", "n aI t"},
            {"Nile", "n aI l"},
            {"nip", "n I p"},
            {"no", "n @U"},
            {"nod", "n Q d"},
            {"node", "n @U d"},
            {"noise", "n OI z"},
            {"noose", "n u: s"},
            {"nose", "n @U z"},
            {"notch", "n Q tS"},
            {"note", "n @U t"},
            {"nub", "n V b"},
            {"nude", "n u: d"},
            {"nudge", "n V dZ"},
            {"nuke", "n u: k"},
            {"null", "n V l"},
            {"nurse", "n @r s"},
            {"nut", "n V t"},
            {"odd", "Q d"},
            {"ODD", "Q d"},
            {"OFF", "Q f"},
            {"ohm", "@U m"},
            {"oil", "OI l"},
            {"oust", "aU s t"},
            {"owe", "@U"},
            {"owl", "aU l"},
            {"own", "@U n"},
            {"pace", "ph eI s"},
            {"pack", "ph { k"},
            {"pad", "ph { d"},
            {"page", "ph eI dZ"},
            {"pain", "ph eI n"},
            {"paint", "ph eI n t"},
            {"pair", "ph e@"},
            {"pal", "ph { l"},
            {"pale", "ph eI l"},
            {"pall", "ph Q l"},
            {"palm", "ph Q m"},
            {"pan", "ph { n"},
            {"pant", "ph { n t"},
            {"par", "ph Q@"},
            {"pare", "ph e@"},
            {"park", "ph Q@ k"},
            {"parked", "ph Q@ k t"},
            {"part", "ph Q@ t"},
            {"pass", "ph { s"},
            {"past", "ph { s t"},
            {"paste", "ph eI s t"},
            {"pat", "ph { t"},
            {"patch", "ph { tS"},
            {"pause", "ph O: z"},
            {"pave", "ph eI v"},
            {"paw", "ph O:"},
            {"pawn", "ph O: n"},
            {"pay", "ph eI"},
            {"peace", "ph i: s"},
            {"peal", "ph i: l"},
            {"pearl", "ph @r l"},
            {"peat", "ph i: t"},
            {"peck", "ph e k"},
            {"peek", "ph i: k"},
            {"peel", "ph i: l"},
            {"peep", "ph i: p"},
            {"peg", "ph e g"},
            {"pelt", "ph e l t"},
            {"pen", "ph e n"},
            {"pep", "ph e p"},
            {"perch", "ph @r tS"},
            {"pet", "ph e t"},
            {"phase", "f eI z"},
            {"phone", "f @U n"},
            {"phrase", "f r eI z"},
            {"pick", "ph I k"},
            {"piece", "ph i: s"},
            {"pig", "ph I g"},
            {"pile", "ph aI l"},
            {"pimp", "ph I m p"},
            {"pin", "ph I n"},
            {"pinch", "ph I n tS"},
            {"ping", "ph I N"},
            {"pink", "ph I N k"},
            {"pipe", "ph aI p"},
            {"pique", "ph i: k"},
            {"pit", "ph I t"},
            {"pitch", "ph I tS"},
            {"pitched", "ph I tS t"},
            {"pith", "ph I T"},
            {"place", "ph l eI s"},
            {"plague", "ph l eI g"},
            {"plain", "ph l eI n"},
            {"plan", "ph l { n"},
            {"plane", "ph l eI n"},
            {"plank", "ph l { N k"},
            {"plant", "ph l { n t"},
            {"plate", "ph l eI t"},
            {"play", "ph l eI"},
            {"played", "ph l eI d"},
            {"plead", "ph l i: d"},
            {"please", "ph l i: z"},
            {"pleat", "ph l i: t"},
            {"pledge", "ph l e dZ"},
            {"plight", "ph l aI t"},
            {"plop", "ph l Q p"},
            {"plot", "ph l Q t"},
            {"plow", "ph l aU"},
            {"pluck", "ph l V k"},
            {"PLUCKED", "ph l V k t"},
            {"plug", "ph l V g"},
            {"plugged", "ph l V g d"},
            {"plumb", "ph l V m"},
            {"plume", "ph l u: m"},
            {"plump", "ph l V m p"},
            {"plunge", "ph l V n dZ"},
            {"plunk", "ph l V N k"},
            {"plush", "ph l V S"},
            {"ply", "ph l aI"},
            {"poach", "ph @U tS"},
            {"pock", "ph Q k"},
            {"pod", "ph Q d"},
            {"point", "ph OI n t"},
            {"poise", "ph OI z"},
            {"poke", "ph @U k"},
            {"pole", "ph @U l"},
            {"poll", "ph @U l"},
            {"pomp", "ph Q m p"},
            {"pool", "ph u: l"},
            {"poor", "ph U@"},
            {"POOR", "ph U@"},
            {"pop", "ph Q p"},
            {"pope", "ph @U p"},
            {"pore", "ph O@"},
            {"port", "ph O@ t"},
            {"pose", "ph @U z"},
            {"posed", "ph @U z d"},
            {"post", "ph @U s t"},
            {"pot", "ph Q t"},
            {"pouch", "ph aU tS"},
            {"pounce", "ph aU n s"},
            {"pound", "ph aU n d"},
            {"pour", "ph O@"},
            {"pout", "ph aU t"},
            {"praise", "ph r eI z"},
            {"prawn", "ph r O: n"},
            {"pray", "ph r eI"},
            {"prayer", "ph r e@"},
            {"preach", "ph r i: tS"},
            {"press", "ph r e s"},
            {"prey", "ph r eI"},
            {"price", "ph r aI s"},
            {"prick", "ph r I k"},
            {"pride", "ph r aI d"},
            {"priest", "ph r i: s t"},
            {"prime", "ph r aI m"},
            {"prince", "ph r I n s"},
            {"print", "ph r I n t"},
            {"pro", "ph r @U"},
            {"probe", "ph r @U b"},
            {"prod", "ph r Q d"},
            {"prompt", "ph r Q m p t"},
            {"prone", "ph r @U n"},
            {"prong", "ph r O: N"},
            {"proof", "ph r u: f"},
            {"prop", "ph r Q p"},
            {"prose", "ph r @U z"},
            {"Proust", "ph r aU s t"},
            {"prove", "ph r u: v"},
            {"prowl", "ph r aU l"},
            {"pry", "ph r aI"},
            {"psalm", "s Q l m"},
            {"Psalm", "s Q l m"},
            {"puff", "ph V f"},
            {"pull", "ph U l"},
            {"pulp", "ph V l p"},
            {"pulse", "ph V l s"},
            {"pump", "ph V m p"},
            {"pun", "ph V n"},
            {"punch", "ph V n tS"},
            {"punt", "ph V n t"},
            {"pup", "ph V p"},
            {"pure", "ph j U@"},
            {"purge", "ph @r dZ"},
            {"purr", "ph @r"},
            {"push", "ph U S"},
            {"put", "ph U t"},
            {"putt", "ph V t"},
            {"quack", "kh w { k"},
            {"quaint", "kh w eI n t"},
            {"queen", "kh w i: n"},
            {"quest", "kh w e s t"},
            {"queue", "kh j u:"},
            {"quick", "kh w I k"},
            {"quilt", "kh w I l t"},
            {"quiz", "kh w I z"},
            {"quote", "kh w @U t"},
            {"race", "r eI s"},
            {"rack", "r { k"},
            {"raft", "r { f t"},
            {"rag", "r { g"},
            {"rage", "r eI dZ"},
            {"raid", "r eI d"},
            {"rail", "r eI l"},
            {"rain", "r eI n"},
            {"raise", "r eI z"},
            {"rake", "r eI k"},
            {"ram", "r { m"},
            {"ramp", "r { m p"},
            {"ranch", "r { n tS"},
            {"range", "r eI n dZ"},
            {"rank", "r { N k"},
            {"rant", "r { n t"},
            {"rap", "r { p"},
            {"rape", "r eI p"},
            {"rare", "r e@"},
            {"rash", "r { S"},
            {"rasp", "r { s p"},
            {"rat", "r { t"},
            {"rate", "r eI t"},
            {"rave", "r eI v"},
            {"raw", "r Q"},
            {"RAW", "r Q"},
            {"ray", "r eI"},
            {"reach", "r i: tS"},
            {"read", "r e d"},
            {"real", "r i: l"},
            {"ream", "r i: m"},
            {"reap", "r i: p"},
            {"rear", "r I@"},
            {"red", "r e d"},
            {"reed", "r i: d"},
            {"reef", "r i: f"},
            {"reek", "r i: k"},
            {"reel", "r i: l"},
            {"reign", "r eI n"},
            {"rein", "r eI n"},
            {"rent", "r e n t"},
            {"rest", "r e s t"},
            {"rhyme", "r aI m"},
            {"rib", "r I b"},
            {"rice", "r aI s"},
            {"rich", "r I tS"},
            {"rick", "r I k"},
            {"rid", "r I d"},
            {"ride", "r aI d"},
            {"ridge", "r I dZ"},
            {"ridged", "r I dZ d"},
            {"riff", "r I f"},
            {"rig", "r I g"},
            {"right", "r aI t"},
            {"rim", "r I m"},
            {"ring", "r I N"},
            {"rinse", "r I n s"},
            {"rip", "r I p"},
            {"rise", "r aI z"},
            {"risk", "r I s k"},
            {"rite", "r aI t"},
            {"ritz", "r I t s"},
            {"roach", "r @U tS"},
            {"roan", "r @U n"},
            {"roar", "r O@"},
            {"roast", "r @U s t"},
            {"rob", "r Q b"},
            {"robe", "r @U b"},
            {"rock", "r Q k"},
            {"roll", "r @U l"},
            {"romp", "r Q m p"},
            {"roof", "r u: f"},
            {"room", "r u: m"},
            {"roost", "r u: s t"},
            {"root", "r u: t"},
            {"rope", "r @U p"},
            {"rose", "r @U z"},
            {"rouge", "r u: Z"},
            {"rough", "r V f"},
            {"ROUGH", "r V f"},
            {"round", "r aU n d"},
            {"row", "r @U"},
            {"rub", "r V b"},
            {"ruff", "r V f"},
            {"rule", "r u: l"},
            {"run", "r V n"},
            {"rush", "r V S"},
            {"rust", "r V s t"},
            {"rut", "r V t"},
            {"sack", "s { k"},
            {"sad", "s { d"},
            {"SAD", "s { d"},
            {"safe", "s eI f"},
            {"sag", "s { g"},
            {"sail", "s eI l"},
            {"saint", "s eI n t"},
            {"salt", "s O: l t"},
            {"salve", "s Q v"},
            {"sand", "s { n d"},
            {"sap", "s { p"},
            {"sass", "s { s"},
            {"sauce", "s O: s"},
            {"save", "s eI v"},
            {"SAVED", "s eI v d"},
            {"saw", "s O:"},
            {"say", "s eI"},
            {"scab", "s k { b"},
            {"scald", "s k O: l d"},
            {"scale", "s k eI l"},
            {"scalp", "s k { l p"},
            {"scam", "s k { m"},
            {"scan", "s k { n"},
            {"scar", "s k Q@"},
            {"SCARCE", "s k e@ s"},
            {"scare", "s k e@"},
            {"scarf", "s k Q@ f"},
            {"scent", "s e n t"},
            {"scheme", "s k i: m"},
            {"school", "s k u: l"},
            {"scoff", "s k O: f"},
            {"scold", "s k @U l d"},
            {"scoop", "s k u: p"},
            {"scope", "s k @U p"},
            {"scorch", "s k O@ tS"},
            {"score", "s k O@"},
            {"scotch", "s k Q tS"},
            {"Scots", "s k Q t s"},
            {"scourge", "s k @r dZ"},
            {"scout", "s k aU t"},
            {"scowl", "s k aU l"},
            {"scrape", "s k r eI p"},
            {"scratch", "s k r { tS"},
            {"scream", "s k r i: m"},
            {"screech", "s k r i: tS"},
            {"screen", "s k r i: n"},
            {"screw", "s k r u:"},
            {"scribe", "s k r aI b"},
            {"script", "s k r I p t"},
            {"scroll", "s k r @U l"},
            {"scrounge", "s k r aU n dZ"},
            {"scrub", "s k r V b"},
            {"scrunch", "s k r V n tS"},
            {"scud", "s k V d"},
            {"scuff", "s k V f"},
            {"scull", "s k V l"},
            {"sculpt", "s k V l p t"},
            {"scum", "s k V m"},
            {"seal", "s i: l"},
            {"seam", "s i: m"},
            {"search", "s @r tS"},
            {"seat", "s i: t"},
            {"sect", "s e k t"},
            {"sedge", "s e dZ"},
            {"see", "s i:"},
            {"seed", "s i: d"},
            {"seek", "s i: k"},
            {"seep", "s i: p"},
            {"seer", "s i: r"},
            {"seize", "s i: z"},
            {"self", "s e l f"},
            {"sell", "s e l"},
            {"send", "s e n d"},
            {"sense", "s e n s"},
            {"serf", "s @r f"},
            {"serve", "s @r v"},
            {"set", "s e t"},
            {"sew", "s @U"},
            {"sex", "s e k s"},
            {"shade", "S eI d"},
            {"shaft", "S { f t"},
            {"shag", "S { g"},
            {"shake", "S eI k"},
            {"shame", "S eI m"},
            {"shank", "S { N k"},
            {"shape", "S eI p"},
            {"shaped", "S eI p t"},
            {"share", "S e@"},
            {"shark", "S Q@ k"},
            {"sharp", "S Q@ p"},
            {"SHARP", "S Q@ p"},
            {"shave", "S eI v"},
            {"Shaw", "S O:"},
            {"shear", "S I@"},
            {"shears", "S i: r z"},
            {"sheathe", "S i: D"},
            {"shed", "S e d"},
            {"sheet", "S i: t"},
            {"sheik", "S i: k"},
            {"shell", "S e l"},
            {"shelve", "S e l v"},
            {"shield", "S i: l d"},
            {"shift", "S I f t"},
            {"shill", "S I l"},
            {"shine", "S aI n"},
            {"ship", "S I p"},
            {"shirr", "S @r"},
            {"shirt", "S @r t"},
            {"shit", "S i: t"},
            {"shock", "S Q k"},
            {"shoe", "S u:"},
            {"shoot", "S u: t"},
            {"shop", "S Q p"},
            {"shore", "S O@"},
            {"SHORT", "S O@ t"},
            {"shout", "S aU t"},
            {"shove", "S V v"},
            {"show", "S @U"},
            {"shred", "S r e d"},
            {"shriek", "S r i: k"},
            {"shrieked", "S r i: k t"},
            {"shrill", "S r I l"},
            {"shrimp", "S r I m p"},
            {"shrine", "S r aI n"},
            {"shrink", "S r I N k"},
            {"shroud", "S r aU d"},
            {"shrub", "S r V b"},
            {"shrug", "S r V g"},
            {"shuck", "S V k"},
            {"shun", "S V n"},
            {"shunt", "S V n t"},
            {"SHUT", "S V t"},
            {"shy", "S aI"},
            {"sick", "s I k"},
            {"sieve", "s I v"},
            {"sift", "s I f t"},
            {"sigh", "s aI"},
            {"sight", "s aI t"},
            {"sign", "s aI n"},
            {"Sikh", "s i: k"},
            {"silt", "s I l t"},
            {"sin", "s I n"},
            {"sing", "s I N"},
            {"singe", "s I n dZ"},
            {"sink", "s I N k"},
            {"Sioux", "s u:"},
            {"sip", "s I p"},
            {"sit", "s I t"},
            {"site", "s aI t"},
            {"size", "s aI z"},
            {"skate", "s k eI t"},
            {"sketch", "s k e tS"},
            {"skew", "s k j u:"},
            {"ski", "s k i:"},
            {"skid", "s k I d"},
            {"skim", "s k I m"},
            {"skimp", "s k I m p"},
            {"skin", "s k I n"},
            {"skip", "s k I p"},
            {"slack", "s l { k"},
            {"slam", "s l { m"},
            {"slang", "s l { N"},
            {"slant", "s l { n t"},
            {"slap", "s l { p"},
            {"slash", "s l { S"},
            {"slat", "s l { t"},
            {"slate", "s l eI t"},
            {"Slav", "s l Q v"},
            {"slave", "s l eI v"},
            {"sled", "s l e d"},
            {"sledge", "s l e dZ"},
            {"sleek", "s l i: k"},
            {"sleep", "s l i: p"},
            {"sleet", "s l i: t"},
            {"sleuth", "s l u: T"},
            {"slice", "s l aI s"},
            {"slick", "s l I k"},
            {"slide", "s l aI d"},
            {"slight", "s l aI t"},
            {"slime", "s l aI m"},
            {"sling", "s l I N"},
            {"slip", "s l I p"},
            {"slit", "s l I t"},
            {"slop", "s l Q p"},
            {"slope", "s l @U p"},
            {"slot", "s l Q t"},
            {"slouch", "s l aU tS"},
            {"slough", "s l V f"},
            {"slow", "s l @U"},
            {"SLOW", "s l @U"},
            {"slug", "s l V g"},
            {"sluice", "s l u: s"},
            {"slum", "s l V m"},
            {"slump", "s l V m p"},
            {"slur", "s l @r"},
            {"slush", "s l V S"},
            {"smack", "s m { k"},
            {"small", "s m O: l"},
            {"SMALL", "s m O: l"},
            {"smart", "s m Q@ t"},
            {"smash", "s m { S"},
            {"smear", "s m I@"},
            {"smell", "s m e l"},
            {"smelt", "s m e l t"},
            {"smile", "s m aI l"},
            {"smirk", "s m @r k"},
            {"smock", "s m Q k"},
            {"smog", "s m Q g"},
            {"smoke", "s m @U k"},
            {"smooth", "s m u: D"},
            {"smudge", "s m V dZ"},
            {"smug", "s m V g"},
            {"smut", "s m V t"},
            {"snag", "s n { g"},
            {"snail", "s n eI l"},
            {"snake", "s n eI k"},
            {"snap", "s n { p"},
            {"snare", "s n e@"},
            {"snarl", "s n Q@ l"},
            {"snatch", "s n { tS"},
            {"sneak", "s n i: k"},
            {"sneer", "s n I@"},
            {"sneeze", "s n i: z"},
            {"sniff", "s n I f"},
            {"snip", "s n I p"},
            {"snipe", "s n aI p"},
            {"snob", "s n Q b"},
            {"snoop", "s n u: p"},
            {"snooze", "s n u: z"},
            {"snore", "s n O@"},
            {"snort", "s n O@ t"},
            {"snot", "s n O: t"},
            {"snow", "s n @U"},
            {"snub", "s n V b"},
            {"snuff", "s n V f"},
            {"snug", "s n V g"},
            {"soak", "s @U k"},
            {"soap", "s @U p"},
            {"soar", "s O@"},
            {"sob", "s Q b"},
            {"sod", "s Q d"},
            {"soft", "s Q f t"},
            {"SOFT", "s Q f t"},
            {"sole", "s @U l"},
            {"solve", "s Q l v"},
            {"son", "s V n"},
            {"song", "s O: N"},
            {"soot", "s U t"},
            {"soothe", "s u: D"},
            {"sop", "s Q p"},
            {"sort", "s O@ t"},
            {"sought", "s O: t"},
            {"sound", "s aU n d"},
            {"source", "s O@ s"},
            {"SOUTH", "s aU T"},
            {"sow", "s aU"},
            {"space", "s p eI s"},
            {"spade", "s p eI d"},
            {"span", "s p { n"},
            {"spank", "s p { N k"},
            {"spar", "s p Q@"},
            {"spare", "s p e@"},
            {"spark", "s p Q@ k"},
            {"sparse", "s p Q@ s"},
            {"spat", "s p { t"},
            {"spawn", "s p Q n"},
            {"speak", "s p i: k"},
            {"spear", "s p I@"},
            {"speck", "s p e k"},
            {"speech", "s p i: tS"},
            {"speed", "s p i: d"},
            {"spell", "s p e l"},
            {"spend", "s p e n d"},
            {"sperm", "s p @r m"},
            {"sphere", "s f I@"},
            {"spice", "s p aI s"},
            {"spiel", "s p i: l"},
            {"spike", "s p aI k"},
            {"spill", "s p I l"},
            {"spin", "s p I n"},
            {"spine", "s p aI n"},
            {"spit", "s p I t"},
            {"splash", "s p l { S"},
            {"splat", "s p l { t"},
            {"spleen", "s p l i: n"},
            {"splice", "s p l aI s"},
            {"splint", "s p l I n t"},
            {"split", "s p l I t"},
            {"splurge", "s p l @r dZ"},
            {"spoil", "s p OI l"},
            {"sponge", "s p V n dZ"},
            {"spoof", "s p u: f"},
            {"spook", "s p u: k"},
            {"spool", "s p u: l"},
            {"spoon", "s p u: n"},
            {"sport", "s p O@ t"},
            {"spot", "s p Q t"},
            {"spouse", "s p aU s"},
            {"spout", "s p aU t"},
            {"sprain", "s p r eI n"},
            {"sprawl", "s p r O: l"},
            {"spray", "s p r eI"},
            {"spread", "s p r e d"},
            {"spree", "s p r i:"},
            {"sprint", "s p r I n t"},
            {"sprout", "s p r aU t"},
            {"spur", "s p @r"},
            {"spurt", "s p @r t"},
            {"spy", "s p aI"},
            {"squall", "s k w O: l"},
            {"square", "s k w e@"},
            {"SQUARE", "s k w e@"},
            {"squashed", "s k w Q S t"},
            {"squat", "s k w Q t"},
            {"squawk", "s k w O: k"},
            {"squeak", "s k w i: k"},
            {"squeal", "s k w i: l"},
            {"squeeze", "s k w i: z"},
            {"squelch", "s k w e l tS"},
            {"squint", "s k w I n t"},
            {"squire", "s k w aI r"},
            {"squirt", "s k w @r t"},
            {"stab", "s t { b"},
            {"stack", "s t { k"},
            {"stacked", "s t { k t"},
            {"staff", "s t { f"},
            {"stage", "s t eI dZ"},
            {"stain", "s t eI n"},
            {"stake", "s t eI k"},
            {"STALE", "s t eI l"},
            {"stalk", "s t O: k"},
            {"stall", "s t O: l"},
            {"stamp", "s t { m p"},
            {"stance", "s t { n s"},
            {"stand", "s t { n d"},
            {"star", "s t Q@"},
            {"starch", "s t Q@ tS"},
            {"stare", "s t e@"},
            {"stark", "s t Q@ k"},
            {"start", "s t Q@ t"},
            {"starve", "s t Q@ v"},
            {"state", "s t eI t"},
            {"stave", "s t eI v"},
            {"stay", "s t eI"},
            {"steal", "s t i: l"},
            {"stealth", "s t e l T"},
            {"steam", "s t i: m"},
            {"steel", "s t i: l"},
            {"steep", "s t i: p"},
            {"STEEP", "s t i: p"},
            {"steer", "s t I@"},
            {"stem", "s t e m"},
            {"step", "s t e p"},
            {"stern", "s t @r n"},
            {"stew", "s t u:"},
            {"stick", "s t I k"},
            {"stiff", "s t I f"},
            {"still", "s t I l"},
            {"STILL", "s t I l"},
            {"sting", "s t I N"},
            {"stink", "s t I N k"},
            {"stint", "s t I n t"},
            {"stir", "s t @r"},
            {"stitch", "s t I tS"},
            {"stock", "s t Q k"},
            {"stoke", "s t @U k"},
            {"stomp", "s t Q m p"},
            {"stone", "s t @U n"},
            {"stooge", "s t u: dZ"},
            {"stool", "s t u: l"},
            {"stoop", "s t u: p"},
            {"stop", "s t Q p"},
            {"store", "s t O@"},
            {"storm", "s t O@ m"},
            {"stout", "s t aU t"},
            {"stow", "s t @U"},
            {"strafe", "s t r eI f"},
            {"straight", "s t r eI t"},
            {"STRAIGHT", "s t r eI t"},
            {"strain", "s t r eI n"},
            {"strange", "s t r eI n dZ"},
            {"strap", "s t r { p"},
            {"straw", "s t r O:"},
            {"stray", "s t r eI"},
            {"streak", "s t r i: k"},
            {"stream", "s t r i: m"},
            {"strength", "s t r e N k T"},
            {"stress", "s t r e s"},
            {"stretch", "s t r e tS"},
            {"strew", "s t r u:"},
            {"stride", "s t r aI d"},
            {"strike", "s t r aI k"},
            {"string", "s t r I N"},
            {"strip", "s t r I p"},
            {"stripe", "s t r aI p"},
            {"stroke", "s t r @U k"},
            {"stroll", "s t r @U l"},
            {"strum", "s t r V m"},
            {"strung", "s t r V N"},
            {"strut", "s t r V t"},
            {"stud", "s t V d"},
            {"stuff", "s t V f"},
            {"stump", "s t V m p"},
            {"stun", "s t V n"},
            {"stunt", "s t V n t"},
            {"style", "s t aI l"},
            {"suck", "s V k"},
            {"suds", "s V d z"},
            {"sulk", "s V l k"},
            {"sum", "s V m"},
            {"sun", "s V n"},
            {"sup", "s V p"},
            {"sure", "S U@"},
            {"surf", "s @r f"},
            {"surge", "s @r dZ"},
            {"swab", "s w Q b"},
            {"swamp", "s w Q m p"},
            {"swarm", "s w O@ m"},
            {"swat", "s w Q t"},
            {"swathe", "s w Q D"},
            {"sway", "s w eI"},
            {"swear", "s w e@"},
            {"sweat", "s w e t"},
            {"sweep", "s w i: p"},
            {"sweet", "s w i: t"},
            {"swell", "s w e l"},
            {"swerve", "s w @r v"},
            {"swift", "s w I f t"},
            {"swill", "s w I l"},
            {"swim", "s w I m"},
            {"swing", "s w I N"},
            {"swipe", "s w aI p"},
            {"swish", "s w I S"},
            {"Swiss", "s w I s"},
            {"switch", "s w I tS"},
            {"swoop", "s w u: p"},
            {"tack", "th { k"},
            {"tag", "th { g"},
            {"tail", "th eI l"},
            {"take", "th eI k"},
            {"talc", "th { l k"},
            {"talk", "th O: k"},
            {"tame", "th eI m"},
            {"tamp", "th { m p"},
            {"tan", "th { n"},
            {"tank", "th { N k"},
            {"tap", "th { p"},
            {"tape", "th eI p"},
            {"tar", "th Q@"},
            {"tart", "th Q@ t"},
            {"task", "th { s k"},
            {"taste", "th eI s t"},
            {"tat", "th { t"},
            {"taut", "th O: t"},
            {"tax", "th { k s"},
            {"teach", "th i: tS"},
            {"team", "th i: m"},
            {"tear", "th e@"},
            {"tease", "th i: z"},
            {"tee", "th i:"},
            {"teem", "th i: m"},
            {"teethe", "th i: D"},
            {"tell", "th e l"},
            {"tempt", "th e m p t"},
            {"tend", "th e n d"},
            {"tense", "th e n s"},
            {"tent", "th e n t"},
            {"term", "th @r m"},
            {"test", "th e s t"},
            {"text", "th e k s t"},
            {"Thai", "th aI"},
            {"thane", "T eI n"},
            {"thatch", "T { tS"},
            {"thaw", "T O:"},
            {"theme", "T i: m"},
            {"there", "D e@"},
            {"thin", "T I n"},
            {"THIN", "T I n"},
            {"think", "T I N k"},
            {"thirst", "T @r s t"},
            {"thought", "T O: t"},
            {"thrash", "T r { S"},
            {"thread", "T r e d"},
            {"thrill", "T r I l"},
            {"throat", "T r @U t"},
            {"throb", "T r Q b"},
            {"throne", "T r @U n"},
            {"throng", "T r O: N"},
            {"throw", "T r @U"},
            {"thrust", "T r V s t"},
            {"thud", "T V d"},
            {"thumb", "T V m"},
            {"thump", "T V m p"},
            {"thwart", "T w O@ t"},
            {"tick", "th I k"},
            {"tide", "th aI d"},
            {"tie", "th aI"},
            {"tier", "th i: r"},
            {"tiered", "th i: r d"},
            {"tight", "th aI t"},
            {"TIGHT", "th aI t"},
            {"tile", "th aI l"},
            {"till", "th I l"},
            {"tilt", "th I l t"},
            {"time", "th aI m"},
            {"tin", "th I n"},
            {"ting", "th I N"},
            {"tint", "th I n t"},
            {"tip", "th I p"},
            {"tithe", "th aI D"},
            {"toast", "th @U s t"},
            {"toe", "th @U"},
            {"toll", "th @U l"},
            {"tone", "th @U n"},
            {"tongue", "th V N"},
            {"tool", "th u: l"},
            {"toot", "th u: t"},
            {"tooth", "th u: T"},
            {"top", "th Q p"},
            {"torch", "th O@ tS"},
            {"toss", "th O: s"},
            {"touch", "th V tS"},
            {"tour", "th U@"},
            {"tout", "th aU t"},
            {"tow", "th @U"},
            {"town", "th aU n"},
            {"toy", "th OI"},
            {"trace", "th r eI s"},
            {"track", "th r { k"},
            {"trade", "th r eI d"},
            {"trail", "th r eI l"},
            {"train", "th r eI n"},
            {"tram", "th r { m"},
            {"tramp", "th r { m p"},
            {"trap", "th r { p"},
            {"trash", "th r { S"},
            {"tread", "th r e d"},
            {"treat", "th r i: t"},
            {"tree", "th r i:"},
            {"trek", "th r e k"},
            {"trench", "th r e n tS"},
            {"tribe", "th r aI b"},
            {"trick", "th r I k"},
            {"trill", "th r I l"},
            {"trim", "th r I m"},
            {"trip", "th r I p"},
            {"troll", "th r @U l"},
            {"troop", "th r u: p"},
            {"trot", "th r Q t"},
            {"Troy", "th r OI"},
            {"truck", "th r V k"},
            {"trudge", "th r V dZ"},
            {"true", "th r u:"},
            {"trump", "th r V m p"},
            {"truss", "th r V s"},
            {"trust", "th r V s t"},
            {"truth", "th r u: T"},
            {"try", "th r aI"},
            {"tube", "th u: b"},
            {"tuck", "th V k"},
            {"tug", "th V g"},
            {"tune", "th u: n"},
            {"turn", "th @r n"},
            {"tusk", "th V s k"},
            {"twang", "th w Q N"},
            {"tweak", "th w i: k"},
            {"tweed", "th w i: d"},
            {"tweet", "th w i: t"},
            {"twig", "th w I g"},
            {"twill", "th w I l"},
            {"twin", "th w I n"},
            {"twine", "th w aI n"},
            {"twinge", "th w I n dZ"},
            {"twirl", "th w @r l"},
            {"twist", "th w I s t"},
            {"twitch", "th w I tS"},
            {"type", "th aI p"},
            {"up", "V p"},
            {"urge", "@r dZ"},
            {"use", "j u: s"},
            {"valve", "v { l v"},
            {"vamp", "v { m p"},
            {"vault", "v O: l t"},
            {"veer", "v I@"},
            {"veil", "v eI l"},
            {"vein", "v eI n"},
            {"vent", "v e n t"},
            {"verb", "v @r b"},
            {"verge", "v @r dZ"},
            {"verse", "v @r s"},
            {"vest", "v e s t"},
            {"vet", "v e t"},
            {"vice", "v aI s"},
            {"view", "v j u:"},
        };
        #endregion
        #region KEY_JP
#if JAVA
        public static final String[][] _KEY_JP = {
#else
        public static readonly String[,] _KEY_JP = {
#endif
            {"あ", "a"},
            {"い", "i"},
            {"う", "M"},
            {"え", "e"},
            {"お", "o"},
            {"か", "k a"},
            {"き", "k' i"},
            {"く", "k M"},
            {"け", "k e"},
            {"こ", "k o"},
            {"さ", "s a"},
            {"し", "S i"},
            {"す", "s M"},
            {"せ", "s e"},
            {"そ", "s o"},
            {"た", "t a"},
            {"ち", "tS i"},
            {"つ", "ts M"},
            {"て", "t e"},
            {"と", "t o"},
            {"な", "n a"},
            {"に", "J i"},
            {"ぬ", "n M"},
            {"ね", "n e"},
            {"の", "n o"},
            {"は", "h a"},
            {"ひ", "C i"},
            {"ふ", "p\\ M"},
            {"へ", "h e"},
            {"ほ", "h o"},
            {"ま", "m a"},
            {"み", "m' i"},
            {"む", "m M"},
            {"め", "m e"},
            {"も", "m o"},
            {"や", "j a"},
            {"ゆ", "j M"},
            {"よ", "j o"},
            {"ら", "4 a"},
            {"り", "4' i"},
            {"る", "4 M"},
            {"れ", "4 e "},
            {"ろ", "4 o"},
            {"わ", "w a"},
            {"ゐ", "w i"},
            {"ゑ", "w e"},
            {"を", "o"},
            {"ぁ", "a"},
            {"ぃ", "i"},
            {"ぅ", "M"},
            {"ぇ", "e"},
            {"ぉ", "o"},
            {"が", "g a"},
            {"ぎ", "g' i"},
            {"ぐ", "g M"},
            {"げ", "g e"},
            {"ご", "g o"},
            {"ざ", "dz a"},
            {"じ", "dZ i"},
            {"ず", "dz M"},
            {"ぜ", "dz e"},
            {"ぞ", "dz o"},
            {"だ", "d a"},
            {"ぢ", "dZ i"},
            {"づ", "dz M"},
            {"で", "d e"},
            {"ど", "d o"},
            {"ば", "b a"},
            {"び", "b' i"},
            {"ぶ", "b M"},
            {"べ", "b e"},
            {"ぼ", "b o"},
            {"ぱ", "p a"},
            {"ぴ", "p' i"},
            {"ぷ", "p M"},
            {"ぺ", "p e"},
            {"ぽ", "p o"},
            {"いぇ", "j e"},
            {"うぃ", "w i"},
            {"うぇ", "w e"},
            {"うぉ", "w o"},
            {"きゃ", "k' a"},
            {"きゅ", "k' M"},
            {"きぇ", "k' e"},
            {"きょ", "k' o"},
            {"しゃ", "S a"},
            {"しゅ", "S M"},
            {"しぇ", "S e"},
            {"しょ", "S o"},
            {"ちゃ", "tS a"},
            {"ちゅ", "tS M"},
            {"ちぇ", "tS e"},
            {"ちょ", "tS o"},
            {"にゃ", "J a"},
            {"にゅ", "J M"},
            {"にぇ", "J e"},
            {"にょ", "J o"},
            {"ひゃ", "C a"},
            {"ひゅ", "C M"},
            {"ひぇ", "C e"},
            {"ひょ", "C o"},
            {"ふゃ", "p\\' a"},
            {"ふぃ", "p\\' i"},
            {"ふゅ", "p\\' M"},
            {"ふぇ", "p\\ e"},
            {"みゃ", "m' a"},
            {"みゅ", "m' M"},
            {"みぇ", "m' e"},
            {"みょ", "m' o"},
            {"りゃ", "4' a"},
            {"りゅ", "4' M"},
            {"りぇ", "4' e"},
            {"りょ", "4' o"},
            {"ぎゃ", "g' a"},
            {"ぎゅ", "g' M"},
            {"ぎぇ", "g' e"},
            {"ぎょ", "g' o"},
            {"じゃ", "dZ a"},
            {"じゅ", "dZ M"},
            {"じぇ", "dZ e"},
            {"じょ", "dZ o"},
            {"びゃ", "b' a"},
            {"びゅ", "b' M"},
            {"びぇ", "b' e"},
            {"びょ", "b' o"},
            {"ぴゃ", "p' a"},
            {"ぴゅ", "p' M"},
            {"ぴぇ", "p' e"},
            {"ぴょ", "p' o"},
            {"ふぁ", "p\\ a"},
            {"ふぉ", "p\\ o"},
            {"てゃ", "t' a"},
            {"てぃ", "t' i"},
            {"てゅ", "t' M"},
            {"てぇ", "t' e"},
            {"てょ", "t' o"},
            {"でゃ", "d' a"},
            {"でぃ", "d' i"},
            {"でゅ", "d' M"},
            {"でぇ", "d' e"},
            {"でょ", "d' o"},
            {"すぃ", "s i"},
            {"ずぃ", "dz i"},
            {"とぅ", "t M"},
            {"どぅ", "d M"},
            {"ゃ", "j a"},
            {"ゅ", "j M"},
            {"ょ", "j o"},
            {"ん", "n"},
            {"ア", "a"},
            {"イ", "i"},
            {"ウ", "M"},
            {"エ", "e"},
            {"オ", "o"},
            {"カ", "k a"},
            {"キ", "k' i"},
            {"ク", "k M"},
            {"ケ", "k e"},
            {"コ", "k o"},
            {"サ", "s a"},
            {"シ", "S i"},
            {"ス", "s M"},
            {"セ", "s e"},
            {"ソ", "s o"},
            {"タ", "t a"},
            {"チ", "tS i"},
            {"ツ", "ts M"},
            {"テ", "t e"},
            {"ト", "t o"},
            {"ナ", "n a"},
            {"ニ", "J i"},
            {"ヌ", "n M"},
            {"ネ", "n e"},
            {"ノ", "n o"},
            {"ハ", "h a"},
            {"ヒ", "C i"},
            {"フ", "p\\ M"},
            {"ヘ", "h e"},
            {"ホ", "h o"},
            {"マ", "m a"},
            {"ミ", "m' i"},
            {"ム", "m M"},
            {"メ", "m e"},
            {"モ", "m o"},
            {"ヤ", "j a"},
            {"ユ", "j M"},
            {"ヨ", "j o"},
            {"ラ", "4 a"},
            {"リ", "4' i"},
            {"ル", "4 M"},
            {"レ", "4 e "},
            {"ロ", "4 o"},
            {"ワ", "w a"},
            {"ヰ", "w i"},
            {"ヱ", "w e"},
            {"ヲ", "o"},
            {"ァ", "a"},
            {"ィ", "i"},
            {"ゥ", "M"},
            {"ェ", "e"},
            {"ォ", "o"},
            {"ガ", "g a"},
            {"ギ", "g' i"},
            {"グ", "g M"},
            {"ゲ", "g e"},
            {"ゴ", "g o"},
            {"ザ", "dz a"},
            {"ジ", "dZ i"},
            {"ズ", "dz M"},
            {"ゼ", "dz e"},
            {"ゾ", "dz o"},
            {"ダ", "d a"},
            {"ヂ", "dZ i"},
            {"ヅ", "dz M"},
            {"デ", "d e"},
            {"ド", "d o"},
            {"バ", "b a"},
            {"ビ", "b' i"},
            {"ブ", "b M"},
            {"ベ", "b e"},
            {"ボ", "b o"},
            {"パ", "p a"},
            {"ピ", "p' i"},
            {"プ", "p M"},
            {"ペ", "p e"},
            {"ポ", "p o"},
            {"イェ", "j e"},
            {"ウィ", "w i"},
            {"ウェ", "w e"},
            {"ウォ", "w o"},
            {"キャ", "k' a"},
            {"キュ", "k' M"},
            {"キェ", "k' e"},
            {"キョ", "k' o"},
            {"シャ", "S a"},
            {"シュ", "S M"},
            {"シェ", "S e"},
            {"ショ", "S o"},
            {"チャ", "tS a"},
            {"チュ", "tS M"},
            {"チェ", "tS e"},
            {"チョ", "tS o"},
            {"ニャ", "J a"},
            {"ニュ", "J M"},
            {"ニェ", "J e"},
            {"ニョ", "J o"},
            {"ヒャ", "C a"},
            {"ヒュ", "C M"},
            {"ヒェ", "C e"},
            {"ヒョ", "C o"},
            {"フャ", "p\\' a"},
            {"フィ", "p\\' i"},
            {"フュ", "p\\' M"},
            {"フェ", "p\\ e"},
            {"ミャ", "m' a"},
            {"ミュ", "m' M"},
            {"ミェ", "m' e"},
            {"ミョ", "m' o"},
            {"リャ", "4' a"},
            {"リュ", "4' M"},
            {"リェ", "4' e"},
            {"リョ", "4' o"},
            {"ギャ", "g' a"},
            {"ギュ", "g' M"},
            {"ギェ", "g' e"},
            {"ギョ", "g' o"},
            {"ジャ", "dZ a"},
            {"ジュ", "dZ M"},
            {"ジェ", "dZ e"},
            {"ジョ", "dZ o"},
            {"ビャ", "b' a"},
            {"ビュ", "b' M"},
            {"ビェ", "b' e"},
            {"ビョ", "b' o"},
            {"ピャ", "p' a"},
            {"ピュ", "p' M"},
            {"ピェ", "p' e"},
            {"ピョ", "p' o"},
            {"ファ", "p\\ a"},
            {"フォ", "p\\ o"},
            {"テャ", "t' a"},
            {"ティ", "t' i"},
            {"テュ", "t' M"},
            {"テェ", "t' e"},
            {"テョ", "t' o"},
            {"デャ", "d' a"},
            {"ディ", "d' i"},
            {"デュ", "d' M"},
            {"デェ", "d' e"},
            {"デョ", "d' o"},
            {"スィ", "s i"},
            {"ズィ", "dz i"},
            {"トゥ", "t M"},
            {"ドゥ", "d M"},
            {"ャ", "j a"},
            {"ュ", "j M"},
            {"ョ", "j o"},
            {"ン", "n"},
            {"ヴ", "b M"},
            {"a", "a"},
            {"e", "e"},
            {"i", "i"},
            {"m", "n"},
            {"n", "n"},
            {"o", "o"},
            {"u", "M"},
            {"A", "a"},
            {"E", "e"},
            {"I", "i"},
            {"M", "n"},
            {"N", "n"},
            {"O", "o"},
            {"U", "M"},
            {"ka", "k a"},
            {"ki", "k' i"},
            {"ku", "k M"},
            {"ke", "k e"},
            {"ko", "k o"},
            {"kya", "k' a"},
            {"kyu", "k' M"},
            {"kyo", "k' o"},
            {"sa", "s a"},
            {"si", "s i"},
            {"su", "s M"},
            {"se", "s e"},
            {"so", "s o"},
            {"ta", "t a"},
            {"ti", "t' i"},
            {"tu", "t M"},
            {"te", "t e"},
            {"to", "t o"},
            {"tya", "t' a"},
            {"tyu", "t' M"},
            {"tyo", "t' o"},
            {"na", "n a"},
            {"ni", "J i"},
            {"nu", "n M"},
            {"ne", "n e"},
            {"no", "n o"},
            {"nya", "J a"},
            {"nyu", "J M"},
            {"nyo", "J o"},
            {"ha", "h a"},
            {"hi", "C i"},
            {"he", "h e"},
            {"ho", "h o"},
            {"hya", "C a"},
            {"hyu", "C M"},
            {"hyo", "C o"},
            {"ma", "m a"},
            {"mi", "m' i"},
            {"mu", "m M"},
            {"me", "m e"},
            {"mo", "m o"},
            {"mya", "m' a"},
            {"myu", "m' M"},
            {"myo", "m' o"},
            {"ya", "j a"},
            {"yu", "j M"},
            {"ye", "j e"},
            {"yo", "j o"},
            {"ra", "4 a"},
            {"ri", "4' i"},
            {"ru", "4 M"},
            {"re", "4 e"},
            {"ro", "4 o"},
            {"rya", "4' a"},
            {"ryu", "4' M"},
            {"ryo", "4' o"},
            {"wa", "w a"},
            {"wi", "w i"},
            {"we", "w e"},
            {"wo", "w o"},
            {"ga", "g a"},
            {"gi", "g' i"},
            {"gu", "g M"},
            {"ge", "g e"},
            {"go", "g o"},
            {"gya", "g' a"},
            {"gyu", "g' M"},
            {"gyo", "g' o"},
            {"za", "dz a"},
            {"zi", "dz i"},
            {"zu", "dz M"},
            {"ze", "dz e"},
            {"zo", "dz o"},
            {"da", "d a"},
            {"di", "d' i"},
            {"du", "d M"},
            {"de", "d e"},
            {"do", "d o"},
            {"dya", "d' a"},
            {"dyu", "d' M"},
            {"dyo", "d' o"},
            {"ba", "b a"},
            {"bi", "b' i"},
            {"bu", "b M"},
            {"be", "b e"},
            {"bo", "b o"},
            {"bya", "b' a"},
            {"byu", "b' M"},
            {"byo", "b' o"},
            {"pa", "p a"},
            {"pi", "p' i"},
            {"pu", "p M"},
            {"pe", "p e"},
            {"po", "p o"},
            {"pya", "p' a"},
            {"pyu", "p' M"},
            {"pyo", "p' o"},
            {"sha", "S a"},
            {"shi", "S i"},
            {"shu", "S M"},
            {"sho", "S o"},
            {"tsu", "ts M"},
            {"cha", "tS a"},
            {"chi", "tS i"},
            {"chu", "tS M"},
            {"cho", "tS o"},
            {"fu", "p\\ M"},
            {"ja", "dZ a"},
            {"ji", "dZ i"},
            {"ju", "dZ M"},
            {"jo", "dZ o"},
        };
        #endregion
        #endregion

        #region Static Method and Property
        public static SymbolTable getSymbolTable( int index ) {
            if ( !s_initialized ) {
                loadDictionary();
            }
            if ( 0 <= index && index < s_table.size() ) {
                return s_table.get( index );
            } else {
                return null;
            }
        }

        public static void loadDictionary() {
#if DEBUG
            PortUtil.println( "SymbolTable.LoadDictionary()" );
#endif
            s_default_jp = new SymbolTable( "DEFAULT_JP", _KEY_JP, true );
            s_default_en = new SymbolTable( "DEFAULT_EN", _KEY_EN, true );
            s_table.clear();
            int count = 0;
            s_table.put( count, s_default_en );
            count++;
            s_table.put( count, s_default_jp );
            count++;

            // 辞書フォルダからの読込み
            String editor_path = VocaloSysUtil.getEditorPath( SynthesizerType.VOCALOID2 );
            if ( editor_path != "" ) {
                String path = PortUtil.combinePath( PortUtil.getDirectoryName( editor_path ), "UDIC" );
                if ( !PortUtil.isDirectoryExists( path ) ) {
                    return;
                }
                String[] files = PortUtil.listFiles( path, "*.udc" );
                for ( int i = 0; i < files.Length; i++ ) {
                    files[i] = PortUtil.getFileName( files[i] );
#if DEBUG
                    PortUtil.println( "    files[i]=" + files[i] );
#endif
                    String dict = PortUtil.combinePath( path, files[i] );
                    s_table.put( count, new SymbolTable( dict, true, false ) );
                    count++;
                }
            }

            // 起動ディレクトリ
            String path2 = PortUtil.combinePath( PortUtil.getApplicationStartupPath(), "udic" );
            if ( PortUtil.isDirectoryExists( path2 ) ) {
                String[] files2 = PortUtil.listFiles( path2, "*.eudc" );
                for ( int i = 0; i < files2.Length; i++ ) {
                    files2[i] = PortUtil.getFileName( files2[i] );
#if DEBUG
                    PortUtil.println( "    files2[i]=" + files2[i] );
#endif
                    String dict = PortUtil.combinePath( path2, files2[i] );
                    s_table.put( count, new SymbolTable( dict, false, false ) );
                    count++;
                }
            }
            s_initialized = true;
        }


        public static boolean attatch( String phrase, ByRef<String> result ) {
#if DEBUG
            PortUtil.println( "SymbolTable.Attatch" );
            PortUtil.println( "    phrase=" + phrase );
#endif
            for ( Iterator itr = s_table.keySet().iterator(); itr.hasNext(); ) {
                int key = (Integer)itr.next();
                SymbolTable table = s_table.get( key );
                if ( table.isEnabled() ) {
                    if ( table.attatchImp( phrase, result ) ) {
                        return true;
                    }
                }
            }
            result.value = "a";
            return false;
        }

        public static int getCount() {
            if ( !s_initialized ) {
                loadDictionary();
            }
            return s_table.size();
        }

        public static void changeOrder( Vector<ValuePair<String, Boolean>> list ) {
#if DEBUG
            PortUtil.println( "SymbolTable#changeOrder" );
#endif
            TreeMap<Integer, SymbolTable> buff = new TreeMap<Integer, SymbolTable>();
            for ( Iterator itr = s_table.keySet().iterator(); itr.hasNext(); ) {
                int key = (Integer)itr.next();
                buff.put( key, (SymbolTable)s_table.get( key ).clone() );
            }
            s_table.clear();
            int count = list.size();
            for ( int i = 0; i < count; i++ ) {
                ValuePair<String, Boolean> itemi = list.get( i );
#if DEBUG
                PortUtil.println( "SymbolTable#changeOrder; list[" + i + "]=" + itemi.getKey() + "," + itemi.getValue() );
#endif
                for ( Iterator itr = buff.keySet().iterator(); itr.hasNext(); ) {
                    int key = (Integer)itr.next();
                    SymbolTable table = buff.get( key );
                    if ( table.getName().Equals( itemi.getKey() ) ) {
                        table.setEnabled( itemi.getValue() );
                        s_table.put( i, table );
                        break;
                    }
                }
            }
        }
        #endregion

#if !JAVA
        public object Clone() {
            return clone();
        }
#endif

        public Object clone() {
            SymbolTable ret = new SymbolTable();
            ret.m_dict = new TreeMap<String, String>();
            for ( Iterator itr = m_dict.keySet().iterator(); itr.hasNext(); ) {
                String key = (String)itr.next();
                ret.m_dict.put( key, m_dict.get( key ) );
            }
            ret.m_name = m_name;
            ret.m_enabled = m_enabled;
            return ret;
        }

        private SymbolTable() {
        }

        public String getName() {
            return m_name;
        }

        public boolean isEnabled() {
            return m_enabled;
        }

        public void setEnabled( boolean value ) {
            m_enabled = value;
        }

        public SymbolTable( String path, boolean is_udc_mode, boolean enabled ) {
            m_dict = new TreeMap<String, String>();
            m_enabled = enabled;
            if ( !PortUtil.isFileExists( path ) ) {
                return;
            }
            m_name = PortUtil.getFileName( path );
            BufferedReader sr = null;
            try {
                if ( is_udc_mode ) {
                    sr = new BufferedReader( new InputStreamReader( new FileInputStream( path ), "Shift_JIS" ) );
                    if ( sr == null ) {
                        return;
                    }
                } else {
                    sr = new BufferedReader( new InputStreamReader( new FileInputStream( path ), "UTF8" ) );
                    if ( sr == null ) {
                        return;
                    }
                }
                String line;
                while ( sr.ready() ) {
                    line = sr.readLine();
                    if ( !line.StartsWith( "//" ) ) {
                        String[] spl = PortUtil.splitString( line, new String[] { "\t" }, 2, true );
                        if ( spl.Length >= 2 ) {
                            if ( m_dict.containsKey( spl[0] ) ) {
                                PortUtil.println( "SymbolTable..ctor" );
                                PortUtil.println( "    dictionary already contains key: " + spl[0] );
                            } else {
                                m_dict.put( spl[0], spl[1] );
                            }
                        }
                    }
                }
            } catch ( Exception ex ) {
                PortUtil.println( "SymbolTable..ctor" );
                PortUtil.println( "    " + ex );
            } finally {
                if ( sr != null ) {
                    try {
                        sr.close();
                    } catch ( Exception ex2 ) {
                    }
                }
            }
        }

        private boolean attatchImp( String phrase, ByRef<String> result ) {
            String s = phrase.ToLower();
            if ( m_dict.containsKey( s ) ) {
                result.value = m_dict.get( s );
                return true;
            } else {
                result.value = "a";
                return false;
            }
        }

#if JAVA
        private SymbolTable( String name, String[][] key, boolean enabled ){
#else
        private SymbolTable( String name, String[,] key, boolean enabled ) {
#endif
            m_enabled = enabled;
            m_name = name;
            m_dict = new TreeMap<String, String>();
#if JAVA
            for( int i = 0; i < key.length; i++ ){
                if( m_dict.containsKey( key[i][0] ) ){
                }else{
                    m_dict.put( key[i][0], key[i][1] );
                }
            }
#else
            for ( int i = 0; i < key.GetLength( 0 ); i++ ) {
                if ( m_dict.containsKey( key[i, 0] ) ) {
                } else {
                    m_dict.put( key[i, 0], key[i, 1] );
                }
            }
#endif
        }
    }

#if !JAVA
}
#endif
